### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by KristianUSN** [G-dH/advanced-alttab-window-switcher#1]
I'm on Fedora 34, and this doesn't seem to do anything. Restarted shell and tried both Xorg and Wayland session and neither changes the alt-tab look at all and none of the listed hotkeys do anything

**Comment by G-dH** [comment]
Interesting, I test all on Fedora 34. Show me output from this command, please:

    journalctl /usr/bin/gnome-shell --since "2 days ago" | grep advanced-alt-tab

**Comment by G-dH** [comment]
And make sure you don't use any other extension altering altTab module.

**Comment by G-dH** [comment]
I forgot to mention that this extension is replacement of the "Window switcher", so if you want to use it, you need to set the keyboard shortcut in Gnome Settings, if you don't have it set already.
