### ISSUE TITLE
Filter inconsistencies

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/advanced-alttab-window-switcher#10]
I've found two inconsistencies with filters (using version 11 from extensions page):

1. Setting Window Switcher to "All Windows" works for the keyboard triggered switcher but not the mouse triggered one (it still filters by work space)
2. Setting Window Switcher to "Current Workspace" and App Switcher to "All Windows" causes the following issue: if I use the App Switcher to select an app with windows across multiple work spaces and then toggle the single app mode on that app it will filter by work space again, which means I now have to do an awkward Shift+Q press, while also holding on to Alt, just so I get the windows of the app across all work spaces even though my App Switcher was already configured to show "All Windows" across all work spaces. IMO the App Switcher setting should also apply to the "drill down" feature (app filter).

**Comment by G-dH** [comment]
1. Filter setting is given by the choice in CHC-E, therefore you can have all windows on one corner trigger, ws on the second and single app on the third.
2. You're right, I'll fix it.

If you update AATWS from the repository, you can change the hotkey for switching the filter.

**Comment by UndeadDevel** [comment]
Oops, totally forgot about the setting in CHC-E :smiley:

Good stuff, thanks for the quick responses! :+1:

**Comment by G-dH** [comment]
Thanks for the reports, although I use the extension extensively, I always overlook some details.
