### ISSUE TITLE
[FEATURE] The "Q" key only temporarily toggles filter between all workspaces and current workspace, suggestion to make it permanent

### ISSUE THREAD

**Issue by bakai-taalaibek** [G-dH/advanced-alttab-window-switcher#100]
**Is your feature request related to a problem? Please describe.**
Lets say I set up the windows switcher to only show windows in the current workspace. When I use the windows switcher by pressing Alt+Tab, then I press Q it now shows all windows from all workspaces. But next time I press Alt+Tab it again shows windows from the current workspace.

**Describe the solution you'd like**
I suggest when we press Q after pressing Alt+Tab it toggles filtering between all workspaces and current workspace permanently. So if I initially set up filtering to show windows from all workspaces, then I press Alt+Tab and then Q, next time I use Alt+Tab it shows windows only from current workspace. 

**Describe alternatives you've considered**
Maybe create another shortcut for permanently toggling filtering between all workspaces and current workspace. 

**Additional context**
Maybe if you set up filter to only show windows from current workspace it should automatically stop showing the workspace index?

EDIT: also lets say I initially set up filtering to show windows from all workspaces. Now when I press Alt+Tab it highlights the second window, but if that second window happens to be on another workspace then when I press Q it highlights the first window now. I suggest it prefers highlighting the second window after toggling to show windows from only the current workspace.

**Comment by G-dH** [comment]
The latest update allows you to define an additional hotkey to permanently switch the filter. Available in the main branch, feedback is welcome.

**Comment by bakai-taalaibek** [comment]
I still don't see the new hotkey in the official extension (I didn't take it from github).
