### ISSUE TITLE
[BUG] Window Switcher popup does not work (`JS ERROR: TypeError: box.add is not a function`)

### ISSUE THREAD

**Issue by mkalinski** [G-dH/advanced-alttab-window-switcher#102]
**Describe the bug**
After an upgrade from Gnome 45 to Gnome 46, window switcher popup stopped working.

**To Reproduce**
1. Enable the extension
2. Press `Alt+Tab`
3. Nothing happens, application window is not switched, no popup appears

**Expected behavior**
Active window should be switched to another one, or if `Alt+Tab` is held down for a moment, a window switcher popup should appear.

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Version of the extension: 46.1
 - Source of installation: extension.gnome.org

**Additional context**
Every time I press `Alt+Tab`, the following appears in logs:

```
JS ERROR: TypeError: box.add is not a function
_createHotKeyNumIcon@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherItems.js:542:9
_init@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherItems.js:388:37
AppViewItem@resource:///org/gnome/shell/ui/appDisplay.js:1888:1
AppIcon@resource:///org/gnome/shell/ui/appDisplay.js:2985:4
AppIcon@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherItems.js:280:4
_init@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:89:24
SwitcherList@resource:///org/gnome/shell/ui/switcherPopup.js:391:4
SwitcherList@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:53:4
show@file:///home/mk/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:490:34
_startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1699:23
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by Scoobin** [comment]
I'm getting the same experience, and having found the command to debug it, can confirm it is the same issue.
Debug command:
`sudo journalctl /usr/bin/gnome-shell`

**Comment by G-dH** [comment]
Thanks! It only occurred when the *Show Hotkeys F1-F12 for Direct Activation* option was enabled.
