### ISSUE TITLE
Cannot find gsettings schema

### ISSUE THREAD

**Issue by moalhaddar** [G-dH/advanced-alttab-window-switcher#105]
Hello, first of all, thanks for providing us with this amazing extension.

After tinkering with the extension settings, i wanted to export the settings to save them, however, after checking gsettings schemas on my machine, i cannot find the schema defined for the extension in my machine.

```sh
> gsettings list-schemas | grep org.gnome.shell.extensions.advanced-alt-tab-window-switcher          
# No output

> gsettings list-children org.gnome.shell.extensions.advanced-alt-tab-window-switcher
No such schema “org.gnome.shell.extensions.advanced-alt-tab-window-switcher”
```

Extension Version: 46.2/55
OS: Fedora Linux 40 (Workstation Edition)
GNOME: 46
Windowing system: Wayland
Kernel: Linux 6.8.5-301.fc40.x86_64

Edit: I've managed to show the keys by compiling the schema manually. I've noticed that this happens with all my installed extensions and i'm not sure if this is the default behavior. Read more: https://askubuntu.com/a/1246847

Status: solved!

**Comment by G-dH** [comment]
Hello, it is the default behavior, you can dump the settings directly from the dconf db:
`dconf dump /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/`

**Comment by moalhaddar** [comment]
That's even better! I didn't know that there were available through dconf. Thank you

**Comment by G-dH** [comment]
However, note that only options that were changed from the default value are stored in the dconf. This means that if the default value changes in the future, your configuration can change.
