### ISSUE TITLE
[HOWTO] how to remove apps grid icon from app switcher dock? 

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#108]
Hi,
**Describe the question**
I was able to place the arc menu launcher on the app switcher dock, so I no longer really need the icon that leads to the application grid,

[Screencast from 2024-06-27 20-10-58.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/09129b53-6d0a-4414-818f-65097b85b6f7)

 but I can't find a way to make it disappear from the apps switcher dock ,

![aatws](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/1f5c7ccf-b8c1-4aae-8bf2-f58c513f786d)

I tried to deactivate the "include Show Apps Icon" option found in app switcher -> behavior, 
but it doesn't work even after restarting the shell and even the session.
![aatws1](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/618783b6-5179-418a-b197-2eb0f9264a0a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Version of the extension 46.2
 - Source of installation  GitHub

THANKS.

**Comment by G-dH** [comment]
This option for Dash Mode is not yet implemented.

**Comment by G-dH** [comment]
Option added.

**Comment by JE-Amouel** [comment]
I just tested it and it works very well, just that I had a small problem:

**Description** 
When I tried to deactivate "include show app icon" in the dash mode configuration's menu, the application grid icon disappeared but all the applications that were pinned to the aatws dash did not want it launched, 
so I reset the default parameters of aatws using dconf editor, After I tried pinning apps, and it started working, but just when I tried again to hide the app grid icon in the dash mode configuration 's menu, the icon didn't want to disappear,
 so I remembered that there was the same option in the app switcher configuration menu, and when I also deactivated it, the application grid icon finally disappeared. 

**Issue**
 The "Include Show Apps Icon" option appears twice in the aatws configuration menu, once in the "App Switcher" and again in the "Dash Mode", and to hide the button of the application grid, it must be deactivated in both configurations's menus for the icon to disappear.

**Comment by G-dH** [comment]
Fixed.
How did you install the update? Always use the `git clone / make install` way, otherwise you may need to compile the updated gsettings schema yourself in order to make AATWS fully working.

**Comment by JE-Amouel** [comment]
i did it by first downloading the zip file form the main git branch, then:
`gnome-extensions install --force advanced-alttab-window-switcher-main.zip`

but when i notice that, it wasn't working properly, i  removed the firstly installed aatws, then ;
`gnome-extensions install  advanced-alttab-window-switcher-main.zip`

**Comment by JE-Amouel** [comment]
Overall everything works wonderfully, just that it wasn't easy to realize that you had to deactivate the "Include App Icon" option in two separate menus for this to take effect.

>How did you install the update? Always use the git clone / make install way, otherwise you may need to compile the updated gsettings schema yourself in order to make AATWS fully working.

OK, I'm trying to reinstall based on your recommendations, and I'll let you know.

**Comment by G-dH** [comment]
> Overall everything works wonderfully, just that it wasn't easy to realize that you had to deactivate the "Include Show Apps Icon" option in two separate menus for this to take effect.

That was my mistake, I should work independently now.

**Comment by JE-Amouel** [comment]
Thanks, great work :+1: :100:
