### ISSUE TITLE
[FEATURE] minizing an active window 

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#110]
Hi,
**Is your feature request related to a problem? Please describe.**
It turns out that to minimize an application window the path is a bit long, on the window switcher I have to click on the small menu and access the "hide" option,
and on the application switcher even in the drop down menu I can't find the "hide" option and I have to go back to the window switcher,
I searched in the hotkeys and mouse action's menu, and I found no minimize action.

**Describe the solution you'd like**
it would be nice if the second primary click on a currently active window minimized the window, and also if possible an hotkeys to do the same in dock mode.

**Describe alternatives you've considered**
in a slightly more global view, perhaps add a new action selector for the case where a window is active (focus), and in this menu we could choose actions among which we would find the minimize option
**Additional context**

THANKS

**Comment by G-dH** [comment]
There is no such an option or hotkey. I'm surprised it took this long for someone to come up with this request. You can also use the `Menu` key to open the window context menu and arrow keys or Tab to select the item.

**Comment by JE-Amouel** [comment]
>I'm surprised it took this long for someone to come up with this request

Oh really?

I noticed this since I decided to use aatws as my main dock and soon replacing dtp.

I have already started writing desktop entrier to emulate panel menus
here on first is arc menu as my apps launcher
and on second is [pano](https://github.com/oae/gnome-shell-pano) a clipboard manager
i use [xdotool](https://github.com/jordansissel/xdotool) to emulate appropriate keybinding

**my progress**  

[Screencast from 2024-06-27 23-51-41.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/6f29de00-ea15-43a0-afc0-1550febb9334)

**Desktop entries**
Arc menu
>[Desktop Entry]
Name=ArcMenu
Icon=/home/jason/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/icons/hicolor/16x16/actions/distro-gnome-symbolic.svg
Exec=xdotool key Escape && sleep 0.5 && xdotool key shift+ctrl+alt+U
Type=Application


Pano
>[Desktop Entry]
Name=Pano
Icon=/home/jason/.local/share/gnome-shell/extensions/pano@elhan.io/icons/hicolor/scalable/actions/legacy-indicator-symbolic.svg
Exec=xdotool key Escape && sleep 0.5 && xdotool key shift+super+V
Type=Applicationxdotool key Escape && sleep 0.5 && xdotool key shift+ctrl+alt+U

**Comment by JE-Amouel** [comment]
>I'm surprised it took this long for someone to come up with this request

oh really?
I noticed this since I decided to use aatws fully and I hope to be able to replace dtp with aatws soon

I have already started writing desktop entries to emulate panel menus
in the video, first it's arc menu which would be my application launcher, and second, it's [pano](https://github.com/oae/gnome-shell-pano), a clipboard manager with content preview.

in my desktop entries file, a use [xdotool](https://github.com/jordansissel/xdotool) to emulate appropriate keybinding when i click icon,


**My progress**

[Screencast from 2024-06-27 23-51-41.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/087364b0-1833-4c18-a60c-e66b7238f0c0)



**Desktop entries**
Arc menu
>[Desktop Entry]
Name=ArcMenu
Icon=/home/jason/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/icons/hicolor/16x16/actions/distro-gnome-symbolic.svg
Exec=xdotool key Escape && sleep 0.5 && xdotool key shift+ctrl+alt+U
Type=Application


Pano
>[Desktop Entry]
Name=Pano
Icon=/home/jason/.local/share/gnome-shell/extensions/pano@elhan.io/icons/hicolor/scalable/actions/legacy-indicator-symbolic.svg
Exec=xdotool key Escape && sleep 0.5 && xdotool key shift+super+V
Type=Application

**Comment by G-dH** [comment]
Nice, but CHC-E is faster as a controller for opening ArcMenu or Pano ;)
Have you installed AATWS from this repository?

**Comment by JE-Amouel** [comment]
>Nice, but CHC-E is faster as a controller for opening ArcMenu or Pano ;)

Yes totally,
but the thing is that I want to be able to keep aatws as my main ally, the handling is so simple, quick and intuitive and..., I don't even have enough words to describe it.
for the moment I use CHC-E to trigger arcmenu when I am in the window picker (V-shell) since it is not possible to use aatws in dock mode there ,  so I plan to now trigger the quick settings menu with CHC-E.

>Have you installed AATWS from this repository?

yes

**Comment by JE-Amouel** [comment]
What do you think about it?

**Comment by G-dH** [comment]
I'll add it when I get to it.

**Comment by G-dH** [comment]
Try the latest update, please. The default hotkey is `D`.

**Comment by JE-Amouel** [comment]
I feel like I'm re-discovering aatws again, thank you very much :pray:

**Comment by JE-Amouel** [comment]
I just noticed something with the 'Toggle minimize' Action,
when I try to switch the visibility of a window that is in another workspace, the window changes workspace and now belongs to the current workspace,

**Comment by G-dH** [comment]
That is a feature, if you want to switch to the workspace, just activate the window instead.

**Comment by JE-Amouel** [comment]
Good good 👍 :100:
