### ISSUE TITLE
[HOWTO] change aatws triggering keybinding

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#111]
Hi,
I'm about to discover another side of aatws as a dock (with more to offer),
so I only use it in dock mode with the super key action activated , however I would like to use coverflow for switching applications with the keyboard shortcuts (alt+tab), but on the recent version of gnome the two extensions come into conflict when I use alt+tab, do you have any recommendations so that I can make the two coexist?

as a suggestion; an option to disable the aatws alt+tab behavior ,  i found aatws more comfortable to use with the super key action .

THANKS.

**Comment by G-dH** [comment]
That is possible, of course, but it would cost me a lot of time and you would probably be the only one who would benefit from it. I noticed that you change your desktop configuration very often, so the next question is: for how long would it be good enough for you? Don't take it offensively, I really appreciate your input, you're showing me AATWS's limits, but I never know whether you're just trying something new and might switch to something else tomorrow.

**Comment by JE-Amouel** [comment]
>I really appreciate your input, you're showing me AATWS's limits

I appreciate that you consider that I bring a plus, in reality I often hesitate to make requests for functionality, especially since I tell myself that you probably have better things to do,

>That is possible, of course, but it would cost me a lot of time 

far be it from me to add a bunch of request for the simple purpose of complicating something already so well constructed, I know that sometimes certain request may seem far-fetched, and I leave it up to you to decide whether this is or is not a good idea to guarantee the philosophy and logic of your achievements.

> I noticed that you change your desktop configuration very often...
>but I never know whether you're just trying something new and might switch to something else tomorrow.

I already have an idea of ​​the configuration that I find ideal, and I get there a little more each time there are updates, I want to be able to keep the extensions which allow me to have a mode of healthy and efficient work,
I'm just waiting for aatws to support vertical orientation #98 so that I can definitively replace dtp on my right side of the screen, that's why I'm already preparing the transition by making desktop entries that simulate panel menus.

>for how long would it be good enough for you?

as long as the extension supports the new versions of Gnome, if it is no longer maintained, I think that I will no longer update gnome on the new versions, :joy: 
If gnome teams continues to break compatibility with extensions all the time, I think it will be difficult for everyone, developers and simple users alike.

**Comment by JE-Amouel** [comment]
>Edit: It's not just about keybinding.

but do you think it would still be as tedious if it just involved deactivating the links between the hot keys and aatws?

![Screenshot from 2024-06-30 21-24-28](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/9b0a2f52-eebe-430d-97e2-deb450d81bbf)

**Comment by G-dH** [comment]
AATWS is not a standalone application with its own keybindings, it's an extension of the default Shell switcher.

**Comment by JE-Amouel** [comment]
thanks for your listening :+1:

**Comment by G-dH** [comment]
CoverflowAltTab actually is a separate switcher with its own keybindings.

**Comment by G-dH** [comment]
Can you specify what type of conflict between AATWS and CoverflowAltTab are you experiencing?

**Comment by JE-Amouel** [comment]
When I press alt+tab, the coverflow interface is displayed but all keyboard key actions and mice become broken, In fact it's somewhat logical since both are subscribed to the same keyboard shortcut, but the first time I installed both extensions was on version 42.9 of Gnome, and I expected to see a conflict, but surprisingly on this Version of Gnome, coverflow wraps the behavior of alt+tab of aatws, and therefore there was no problem, and both work really well, but since the recent version of Gnome 45+ , the conflict became quite obvious.

**Comment by G-dH** [comment]
That shouldn't be possible. As I mentioned before, AATWS works the same way as the default switcher as its extension, without any changes in keybindings. CfAT doesn't need the original code and redirects the system shortcuts to its own switcher. It works together on GS 46 without issues that I would notice. Are you still running Ubuntu 23.10?

**Comment by JE-Amouel** [comment]
>Are you still running Ubuntu 23.10?

yes,
i am currently doing my update to version 24.04

**Comment by JE-Amouel** [comment]
>It works together on GS 46 without issues that I would notice. Are you still running Ubuntu 23.10?

now I am on Ubuntu 24.04, with GNOME 46,
and you were right it works without conflict.

Thanks.
