### ISSUE TITLE
[BUG] Tiling popup gets stuck on screen

### ISSUE THREAD

**Issue by harrymander** [G-dH/advanced-alttab-window-switcher#124]
**Describe the bug**

The tiling popup that shows when tiling a window on Ubuntu doesn't go away when a application is selected or Esc key is pressed. 

Additionally, it seems to cause other parts of Gnome to become unresponsive, e.g. task bar, copy-paste, selecting windows in the Activities overview (pressing Super/Windows key). The popup also persists on the lock screen.

So far, the only thing I have found that removes the popup is taking a screenshot!

**To reproduce**

1. In system settings > Ubuntu Desktop: ensure that 'Tiling Popup' is checked
2. Arrange two maximised windows on the same screen with one on top of the other
3. Tile one of the windows e.g. by pressing Alt+Left
4. The tiling popup will show. Clicking on a window will tile it into the empty space, but the popup then becomes unresponsive.

**Expected behaviour**

The popup disappears after selecting a window or pressing Esc.

**Screenshots**

![Screenshot from 2024-10-14 13-40-29](https://github.com/user-attachments/assets/05589bc7-b6e0-4710-9c1a-a69f7ddb7dae)

**Desktop**

* OS: Ubuntu 24.04 (Gnome 46)
* Version of the extension: 47.0/56
* Extension source: extension.gnome.org

**Logs**

```
Oct 14 14:14:20 c032du gnome-shell[16965]: Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.
Oct 14 14:14:20 c032du gnome-shell[16965]: Can't update stage views actor unnamed [MetaSurfaceActorX11] is on because it needs an allocation.
Oct 14 14:14:21 c032du gnome-shell[16965]: Error in size change accounting.
Oct 14 14:14:21 c032du gnome-shell[16965]: JS ERROR: TypeError: this._inputHandler is undefined
                                           vfunc_key_press_event@file:///home/harry/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1651:9
                                           @resource:///org/gnome/shell/ui/init.js:21:20
Oct 14 14:14:22 c032du gnome-shell[16965]: JS ERROR: TypeError: this._timeoutIds is undefined
                                           _delayedDestroy@file:///home/harry/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1102:13
                                           fadeAndDestroy@file:///home/harry/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1097:18
                                           fadeAndDestroy@file:///usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/src/extension/tilingPopup.js:271:15
                                           vfunc_button_press_event@resource:///org/gnome/shell/ui/switcherPopup.js:230:14
                                           vfunc_button_press_event@file:///usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/src/extension/tilingPopup.js:216:22
                                           @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by linuxbastler** [comment]
I didn't have this problem on Ubuntu 24.04. Last weekend I updated to Ubuntu 24.10 and now I have the 
same problem as harrymander describes. The Tiling Popup does stay on screen all time.

**Comment by G-dH** [comment]
Thanks, I'll look into it.

**Comment by pwlsp** [comment]
same here

**Comment by G-dH** [comment]
Please, install AATWS from the main branch and let me know how the fix works for you.

**Comment by linuxbastler** [comment]
yes, the main branch works for me, thanks

**Comment by harrymander** [comment]
Works for me too. Thanks!
