### ISSUE TITLE
[NOT ISSUE] How to set a keybind to get run dialogue-like behaviour

### ISSUE THREAD

**Issue by yusi1** [G-dH/advanced-alttab-window-switcher#13]
Is there any way to start a search mode dialogue that doesn't close when the modifier key is released? I have the option "search mode as default" checked in the extension preferences, so it starts in search mode (and I have to type the app name while holding the modifier, which feels awkward), but when releasing the modifier key the search mode dialogue exits.

Is there any way to start a dialogue in search mode, but not have it exit when the modifier is released, instead have the behaviour that you get when search mode is turned on manually and it doesn't exit when releasing the modifier key, having to press ESC to actually exit the dialogue?

**Comment by yusi1** [comment]
I guess what I'm saying is that want it to act more like a run dialogue than an on-the-fly window switcher / application launcher..

**Comment by yusi1** [comment]
I also saw this in the README:
"Type to Search mode - you can activate it by a hotkey or you can set in preferences to start the switcher directly in this mode so you can type immediately as the popup shows up."

I want the switcher to start directly in this mode and never exit when the modifier is released, the current behaviour is that it exits when the modifier is released, only if I were to manually turn search mode off and then on would it not exit when releasing the modifier key.

**Comment by yusi1** [comment]
Maybe this could be an option in the preferences dialogue? 
`Never close the switcher after releasing the modifier key`

**Comment by G-dH** [comment]
Hi, this is not possible at this time, I'll try to add the option in the future..

**Comment by yusi1** [comment]
> Hi, this is not possible at this time, I'll try to add the option in the future..

No problem, was just suggesting..

**Comment by G-dH** [comment]
Hi, I've just added option that allows you to open the AATWS by pressing and releasing the Super key (which in default opens the Activities overview). When you use the Super key to open the switcher, the switcher stays open until you activate an item or escape it.

**Comment by G-dH** [comment]
The previous statement that the switcher stays open after opening it using the `Super` key is not longer true, however, you can adjust the delay after which the switcher closes in `Common` / `Options for External Trigger` section. You can also hit and release `Ctrl` key to force the switcher to stay on the screen even when the mouse pointer is outside the switcher.

**Comment by max-white** [comment]
Phew! Iam glad that i wasnt the only one that was expecting this behaviour from the beginning. I thought i was going crazy for the last 2 hours finding the option to activate that the finder window stays open after releasing the super key. I guess it is not that easy to implement this feature.
