### ISSUE TITLE
Use of console API on GJS versions < 41

### ISSUE THREAD

**Issue by willmuldrew** [G-dH/advanced-alttab-window-switcher#130]
Hi there

There are 3 places in the legacy version of your great extension where you use the console API which unfortunately only seems to be available from Gnome 41 onwards (see https://gjs-docs.gnome.org/gjs/console.md).  I'm stuck on gnome-shell 40 (corporate environment) so had to install from source and comment out these lines (to avoid the error).  It would be great to have a legacy version without these lines (or with them guarded or using some other logging mechanism) that's available through the standard install channel (then I can recommend to my colleagues more easily).

I'd be happy to send a PR, but I don't know GJS at all, or your preferences on how you'd like it dealt with.  I can have a go, but would be good to have some guidance on how you'd like it implemented. 

```
(base) ➜  advanced-alttab-window-switcher git:(gnome-3.36-44) rg console
extension.js
70:        console.debug(`${this._metadata.name}: enabled`);
104:        console.debug(`${this._metadata.name}: disabled`);

src/actions.js
396:                    console.error(e);
```

Thanks

-Will

**Comment by G-dH** [comment]
Fixed. Thanks!

**Comment by willmuldrew** [comment]
Ah great!  I guess there's the other one in `src/actions.js` but it's tucked away in an error handler - not sure if it's relevant.  Do you know when the update would hit extensions.gnome.org?

**Comment by G-dH** [comment]
> Do you know when the update would hit extensions.gnome.org?

Since today.
