### ISSUE TITLE
The all candidate window number  is 1

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [G-dH/advanced-alttab-window-switcher#14]
How can I make him 1 2 3 4 5 6 7

**Comment by ZhangTianyi-1998** [comment]
![MVIMG_20220218_144141 (1)](https://user-images.githubusercontent.com/37682379/154632068-e9b03e52-facf-42fd-8b13-c602e487e6be.jpg)

**Comment by G-dH** [comment]
It's not possible at the moment, it'd interfere with default hotkeys and search. If you know the favorites order, you can activate it directly (without AATWS) using Super+number.

**Comment by ZhangTianyi-1998** [comment]
thank~
I have another question,I don't quite understand what this 1 stands for
ctrl + tab 
![微信图片_20220218175930](https://user-images.githubusercontent.com/37682379/154660778-16685ffb-7009-4e75-bea0-c128117d0484.jpg)

**Comment by G-dH** [comment]
As I mentioned, in the window switcher it means index of the workspace to which the window belongs. You can remove this indicator in the preferences window if you don't need it.
