### ISSUE TITLE
[Feature Request] Raise only first window in application switcher

### ISSUE THREAD

**Issue by HifeFish** [G-dH/advanced-alttab-window-switcher#15]
I would like the application switcher to only raise the first window of that application instead of all windows. 

Right now I am using this extension: https://extensions.gnome.org/extension/4007/alttab-mod/
that does exactly that, but it would be nice to have the option within AATWS, to be safe from clashing options between the extensions.

**Comment by G-dH** [comment]
Hi, the option is now available in `App Switcher` / `Behavior` section.

**Comment by HifeFish** [comment]
That was so fast I didn't get around to testing it until now. Works like a charm. Thanks for the lightning fast implementation.
