### ISSUE TITLE
App switcher not working

### ISSUE THREAD

**Issue by javohir-abdusattorov** [G-dH/advanced-alttab-window-switcher#16]
I installed this extension, it works very well with dual monitors and typical window switching.

But for some reason, Application switcher (`SUPER` + `TAB`) is not working. It freezes in application switcher pop-up. In pop-up, manually clicking to some extensions not works either.
And there is one more thing that is not working, same app windows switcher (`ALT` + `). It also freezes in pop-up window.
Is there is a version that I needed to install specifically ?

OS: *Pop!_OS 20.04 LTS x86_64*
Desktop env: *GNOME 3.36.7*

**Comment by G-dH** [comment]
Pop! uses heavily customized Shell, therefore conflicts are expected. Open a terminal, execute following command

    journalctl /usr/bin/gnome-shell -f -o cat

then try to use the app switcher and show me the log from the terminal.

**Comment by G-dH** [comment]
I did a test on Pop OS 20.04 and 21.10 with no problems. Probably another extension you have installed is in conflict with the AATWS.

**Comment by javohir-abdusattorov** [comment]
Output of command:

**Comment by javohir-abdusattorov** [comment]
Output of command:
```
JS ERROR: TypeError: this._currentWindow is undefined
_finish@resource:///org/gnome/shell/ui/altTab.js:276:18
vfunc_key_release_event@/home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:1252:26

JS ERROR: TypeError: this._currentWindow is undefined
_finish@resource:///org/gnome/shell/ui/altTab.js:276:18
vfunc_key_release_event@/home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:1252:26

Object .Gjs_advanced-alt-tab_G-dH_github_com_windowSwitcherPopup_WindowSwitcher (0x55d0a46febf0), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55d09da218f0 ==
#0   55d09e323638 i   /home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:3054 (3eee4c1a1ad8 @ 167)
#1   7fff855f04f0 b   self-hosted:1009 (c40256a0cb8 @ 423)
Object .Gjs_advanced-alt-tab_G-dH_github_com_windowSwitcherPopup_WindowSwitcher (0x55d0a46febf0), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55d09da218f0 ==
#0   55d09e323638 i   /home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:3054 (3eee4c1a1ad8 @ 167)
#1   7fff855f04f0 b   self-hosted:1009 (c40256a0cb8 @ 423)
JS ERROR: TypeError: this._currentWindow is undefined
_finish@resource:///org/gnome/shell/ui/altTab.js:276:18
vfunc_key_release_event@/home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:1252:26

JS ERROR: TypeError: this._currentWindow is undefined
_finish@resource:///org/gnome/shell/ui/altTab.js:276:18
vfunc_key_release_event@/home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:1252:26

JS ERROR: TypeError: this._currentWindow is undefined
_finish@resource:///org/gnome/shell/ui/altTab.js:276:18
vfunc_key_release_event@/home/javohir/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/windowSwitcherPopup.js:1252:26

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_showTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:93:4
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateVisible@resource:///org/gnome/shell/ui/overview.js:594:14
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_showTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:93:4
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateVisible@resource:///org/gnome/shell/ui/overview.js:594:14
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_showTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:93:4
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateVisible@resource:///org/gnome/shell/ui/overview.js:594:14
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_hideTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:61:5
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateNotVisible@resource:///org/gnome/shell/ui/overview.js:658:14
hide@resource:///org/gnome/shell/ui/overview.js:633:14
toggle@resource:///org/gnome/shell/ui/overview.js:687:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_hideTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:61:5
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateNotVisible@resource:///org/gnome/shell/ui/overview.js:658:14
hide@resource:///org/gnome/shell/ui/overview.js:633:14
toggle@resource:///org/gnome/shell/ui/overview.js:687:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

Usage of object.actor is deprecated for WorkspaceThumbnail
get@resource:///org/gnome/shell/ui/environment.js:287:29
_hideTitles@/home/javohir/.local/share/gnome-shell/extensions/workspace_titles@ben.santalucia.me/extension.js:61:5
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_animateNotVisible@resource:///org/gnome/shell/ui/overview.js:658:14
hide@resource:///org/gnome/shell/ui/overview.js:633:14
toggle@resource:///org/gnome/shell/ui/overview.js:687:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22
```

**Comment by javohir-abdusattorov** [comment]
> I did a test on Pop OS 20.04 and 21.10 with no problems. Probably another extension you have installed is in conflict with the AATWS.

Yes, I have installed many extensions. And this bug happening because of extensions conflict. But I don't know which one of them is conflicting.

Can you tell what extensions might have conflict ?

**Comment by javohir-abdusattorov** [comment]
> Can you tell what extensions might have conflict ?

I think, I found conflicting extension:
**Workspace titles**: https://extensions.gnome.org/extension/4393/workspace-titles/

**Comment by G-dH** [comment]
Can you list all enabled extensions on your system? I'd say that the problem causes another extension which alters the AltTab switcher code, because it forces AATWS to crash in the function that shouldn't be executed at all.

**Comment by javohir-abdusattorov** [comment]
> Can you list all enabled extensions on your system?

Extensions:

* [AATWS - Advanced Alt-Tab Window Switcher](https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/) by [GdH](https://extensions.gnome.org/accounts/profile/GdH)
* [Activities Configurator](https://extensions.gnome.org/extension/358/activities-configurator/) by [nls1729](https://extensions.gnome.org/accounts/profile/nls1729)
* [Blyr](https://extensions.gnome.org/extension/1251/blyr/) by [yozoon](https://extensions.gnome.org/accounts/profile/yozoon)
* [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/) by [Tudmotu](https://extensions.gnome.org/accounts/profile/Tudmotu)
* [Compiz alike magic lamp effect](https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/) by [hermes83](https://extensions.gnome.org/accounts/profile/hermes83)
* [Compiz alike windows effect](https://extensions.gnome.org/extension/2950/compiz-alike-windows-effect/) by [hermes83](https://extensions.gnome.org/accounts/profile/hermes83)
* [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/) by [michele_g](https://extensions.gnome.org/accounts/profile/michele_g)
* [Hibernate Status Button](https://extensions.gnome.org/extension/755/hibernate-status-button/) by [p91paul](https://extensions.gnome.org/accounts/profile/p91paul)
* [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection/) by [JustPerfection](https://extensions.gnome.org/accounts/profile/JustPerfection)
* [Top Panel Workspace Scroll](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/) by [gfxmonk](https://extensions.gnome.org/accounts/profile/gfxmonk)
* [Transparent Window Moving](https://extensions.gnome.org/extension/1446/transparent-window-moving/) by [Noobsai](https://extensions.gnome.org/accounts/profile/Noobsai)
* [Vitals](https://extensions.gnome.org/extension/1460/vitals/) by [corecoding](https://extensions.gnome.org/accounts/profile/corecoding)
* [WindowOverlay Icons](https://extensions.gnome.org/extension/302/windowoverlay-icons/) by [sustmi](https://extensions.gnome.org/accounts/profile/sustmi)
* [Workspace Titles](https://extensions.gnome.org/extension/4393/workspace-titles/) by [ben8p](https://extensions.gnome.org/accounts/profile/ben8p)
* [Workspaces Bar](https://extensions.gnome.org/extension/3851/workspaces-bar/) by [fthx](https://extensions.gnome.org/accounts/profile/fthx)

This is all extensions. But I already found conflicting one:
* [Workspace Titles](https://extensions.gnome.org/extension/4393/workspace-titles/) by [ben8p](https://extensions.gnome.org/accounts/profile/ben8p)

**Comment by G-dH** [comment]
Interesting, I didn't encounter any conflicts between AATWS and the Workspace Titles.
