### ISSUE TITLE
uhh what?

### ISSUE THREAD

**Issue by dolphin-cat** [G-dH/advanced-alttab-window-switcher#17]
on my primary monitor, window switcher opens
on my secondary monitor, app switcher opens
how do i make app switcher open on both primary and secondary monitors?
it is configured to open in the monitor with the mouse

**Comment by G-dH** [comment]
The switcher can be on one monitor only, you can choose if it will be always the primary monitor or the current one (the one with the mouse pointer). You can move the switcher to another monitor while it's open using `Ctrl+Tab` or `Shift+Arrows` shortcuts.

**Comment by dolphin-cat** [comment]
nvm solved, quick response, how do i disable the windows key thing? i have arc home button and want to use that instead, i am using window switcher, not app switcher

**Comment by dolphin-cat** [comment]
the issue was some sort of bug, re-logging in fixed it

**Comment by dolphin-cat** [comment]
@G-dH

**Comment by G-dH** [comment]
Now I see that I misunderstood your original issue, sorry. The switcher should change its mode from windows to apps only if there's no window to show, so you can launch a new application.

**Comment by dolphin-cat** [comment]
> 

how do i disable that? i have a separate app launcher and don't want it to open with super key

**Comment by dolphin-cat** [comment]
or fine i guess it is ok if it shows me apps, but i don't want it to open with super key

**Comment by dolphin-cat** [comment]
oh and yes you did misunderstand my original issue but i fixed it, it was some sort of bug
i reused the issue for this one cuz too lazy to go make another issue

**Comment by G-dH** [comment]
The Super key mode can be set in the preferences window.

**Comment by dolphin-cat** [comment]
oh i thought it was what opens on alt tab, also what is default for 1, 2 and 3 in mouse control on common tab?

**Comment by dolphin-cat** [comment]
accidentally scrolled over them and changed them

**Comment by G-dH** [comment]
> also what is default for 1, 2 and 3 in mouse control on common tab?

Switch Filter, New Window, Open Preferences
