### ISSUE TITLE
Option to disable wraparound for apps

### ISSUE THREAD

**Issue by drschwabe** [G-dH/advanced-alttab-window-switcher#2]
Noticed the wraparound toggle for workspaces. 
But nice to have one for apps too! 

nice extension, keep up the great work

**Comment by G-dH** [comment]
Thanks for the suggestion, I didn't find this feature very useful as you can use Shift to reverse direction, Home/End keys to select first/last item, Left/Right arrow keys to navigate... But it's not a problem to implement, maybe later.

**Comment by drschwabe** [comment]
Right actually I found it jarring only in context of using arrow keys.    So maybe there could be another option that would let you disable wraparound but applies to when using arrow keys only.   For Tab key I can see how wraparound may be convenient but I personally prefer the arrow keys since I already am used to using those to switch workspaces.   And if the UI blocks navigation vertically (ie- siwthcing workspaces) then it should also block horizontally for consistency. 

The wraparound feels jarring; it has a kind of shuffle effect that loses the user's focus and forces them to recalibrate their eyes as to what thing is selected.    Furthermore, if you have a lot going on you don't necessarily know how many apps you have open on a given workspace; the wraparound makes it not intuitive to understand how many apps are actually on the given workspace relative to others; double worsened if the app windows look similar.  And when it occurs it is difficut to understand where said wraparound event occurred particularly if you are moving fast.        Unless you spend a lot of time looking at each app and treat the cycling navigation as a methodoligical process but I prefer rapid use and a quick block of movement left or right will signal end of apps on that screen and thus we can arrow up or down to rapidly continue the search for that elusive app in a different workspace.   

Anyway, just wanted to share complete perspective for you!   Thanks again, I look forward to continued developments.

**Comment by G-dH** [comment]
OK, you convinced me, I will add this option to the next version, if I don't forget ;) Now I'm working on integrated app launcher that can search for apps when no window matches the pattern you're looking for. If you have any other idea, let me know.

**Comment by G-dH** [comment]
Already in repository.

**Comment by drschwabe** [comment]
Tested it on 2 diff systems, works great - nicely done ! 

Just an idea for one extra level of fidelity, this isn't big deal to me so I'm closing issue but just wanted to part with another "nice to have" in this regard and that is a 'sub option' to enable wraparound but only for tab key: 

```
Wraparound on TAB    ON/OFF
Wraparound on Arrows      ON/OFF
``` 

Having wraparound with 'tab' but not with arrow keys I think is maybe ideal setup at least for me; I think its intutive for example to cycle a small number of apps with a tab and in that case wraparound is useful.   But if you had say 10 windows at that point it might be more useful / intuitive to use arrow keys to cycle through them and thus ensure wraparound doesn't happen which is jarring for any more apps that go beyond the screen dimensions (particularly if you are using large thumbnails for example).   In both cases you would have the option to allow wraparound simply by deciding to use arrows or tab.
