### ISSUE TITLE
Definition of Current Window

### ISSUE THREAD

**Issue by Limaomao821** [G-dH/advanced-alttab-window-switcher#21]
AATWS defines Curent Window as *window where the mouse pointer is currently located*.

Why not *window which you last focused on"? This will benefit many light mouse users, I think?

Thank you!

**Comment by G-dH** [comment]
That's because I use VirtualBox machines and its windows always grab focus when I switch to their workspace. AATWS would jump between monitors while switching workspaces. But adding one more option to the preferences would be possible..

**Comment by G-dH** [comment]
I never remember to add the issue number to the commit description... Option added to the `Default monitor` list.
8ec61eb4c95fa6f9bbd25feb0279095059bfa7e8
