### ISSUE TITLE
Doesnt seem to activate

### ISSUE THREAD

**Issue by dsalch** [G-dH/advanced-alttab-window-switcher#24]
I just upgraded to ubuntu 22.04, and installed this extension to replace "dash to dock". But it seems that it simply wont activate. I never see the change in the switcher screens from the ubuntu stock.  I installed from gnome extensions website, then tried to install through wget and install from github. No change.  The setting page does show up under the "extensions" app and shows activated.

**Comment by dsalch** [comment]
Here are the extensions installed:

![image](https://user-images.githubusercontent.com/23580993/166745806-337b04dd-435c-4d8e-9f10-c56a185d7040.png)

**Comment by G-dH** [comment]
To clarify the basics: The AATWS is an extension of built-in app/window switchers and you can activate it using keyboard shortcuts defined in the GNOME Settings app, in Ubuntu it should be _Alt+Tab, Super+Tab, Alt/Super+~_. AATWS can also be triggered by the _Super_ key if you activate this option in its Settings window (_Common > System Integration_). If you want to trigger the AATWS using a mouse, you need to use the "Custom Hot Corners - Extended" extension.

**Comment by dsalch** [comment]
I have the setting turned on to allow "window switching" on the super key, but it still does nothing. It's still seems the extension app just wont start. 

![image](https://user-images.githubusercontent.com/23580993/166952877-f38e54a3-3008-40b1-a5f1-0bb3fa4da281.png)

**Comment by G-dH** [comment]
Open terminal, execute:
`journalctl /usr/bin/gnome-shell -fo cat`
Press the Super key or Alt+Tab and show me the log output, if any.

**Comment by dsalch** [comment]
I checked and the super key activation is enabled, but it does nothing. I cant find any way to start the app?

![image](https://user-images.githubusercontent.com/23580993/166959850-f921bdec-b33f-4f92-be4c-eb6d06270a5d.png)

**Comment by G-dH** [comment]
If you press Alt+Tab and keep the Alt pressed, do you see the window switcher popup?

**Comment by dsalch** [comment]
What I see is a list of open applications.. Hitting tab moves to the next application

**Comment by G-dH** [comment]
AATWS is a window switcher, it works in two modes: App mode shows icons of open applications and optionally also icons of favorite applications, and Window mode, which shows open windows. Do you see F1, F2, ... overlays on each window preview, when you open the switcher popup using Alt-Tab? Does the switcher popup looks different if you disable the AATWS extension?

**Comment by dsalch** [comment]
OH! wait a minute..  what is the difference between "window" and "app" ?  This does not deal with workspace switching at all? I am terribly sorry.. I assumed "windows " was synonymous with workspace. I am looking for a replacement for dash to dock! Now I understand!

It is working, and I am able to make the small windows for apps that I wanted. WEll, my preference is a workspace switcher, but this will work ok until someone adopts dash to dock.

**Comment by G-dH** [comment]
App switcher groups open windows by application so you can quickly switch between apps instead of individual windows. If you want to switch between windows of selected app, use the key above Tab.
AATWS can navigate between workspaces using Up/Down arrow keys and Page Up/Down keys while the switcher popup is on the screen. If you set Filter mode for the window switcher to Workspace or Monitor, you can see the current list of windows open on the current workspace.
I have AATWS accessible also via hot corners, so if my mouse pointer hits bottom left corner, AATWS with all open apps show up, and if the pointer hits bottom left corner, AATWS with windows of the current workspace show up.

**Comment by dsalch** [comment]
Ok, I understand it now!  And This is really well done, although a bit overwhelming for a newcomer! (not your fault.. it does a LOT).

The one functionality I miss is the tiles of workspaces that dash to dock provided, and then the ability to just use the mouse to change workspaces.  I can duplicate this using the application tiles, but its a lot more work to set up by application instead of by workspace.   Any chance you could add tiles per workspace?

**Comment by dsalch** [comment]
Thinking about it. maybe your approach of tiles per window is actually more effective, IF the layout could be persistent through boots?

**Comment by G-dH** [comment]
> ...and then the ability to just use the mouse to change workspaces.

You can use mouse wheel to switch workspace and you can choose whether you want to scroll over switcher item, background or even outside the popup. Default is scroll over the switcher background, like I use it. With my configuration I can use hot corner to trigger AATWS with windows on the current workspace, immediately rotate mouse wheel to switch workspace and the switcher popup updates its content for each workspace so I can directly switch to any (even hidden or minimized) window on the workspace using the mouse pointer. You can also use mouse to create the window thumbnail, by default by pressing the middle button outside the popup, but you can change it.

> Any chance you could add tiles per workspace?

I thought about it too, but I found it useless. I mostly use one app per workspace (~ 8 Firefox windows, ~ 5 Code windows, few file manager windows, ...) but that doesn't matter, I always need to switch to specific window and AATWS can find it for me as soon as I start typing its title/app name/name of app's executable/... So I hit the Super, type 1-3 characters, hit Enter and the window is focused/app is launching.

**Comment by dsalch** [comment]
Just wanted to drop you a note.  Thanks for your help...

I have been using the extension and I must say that I am impressed. the window tiles do what I need when combined with the activities overview.  (still with it was persistent through reboots). Well done extension (I am a retired CTO of technology companies... so when I say impressed, it has some meaning!)

Also, I found out that for some reason on my PC with a ergonomic keyboard, the super key will simply not activate for anything. has to be a code issue, but it works as expected on my laptop, so its not your issue. 

I have a similiar workstyle except i keep windows grouped in a workspace, and switch workspaces to change "realms".  Having a few tiles for active windows lets me keep an eye on things running in the background quite well. 

Thank you, nicely done!

**Comment by G-dH** [comment]
Thank you, I really appreciate your feedback, it's important for me to see how people use my apps. Users usually convince me to add features they want, if it's possible, but I also need to keep the extension fast and reliable even on slow systems and also focused.

As for your Super key issue, in GNOME it's defined as an 'overlay-key' and although it's mapped to the left Super (Window) key by default, you can remap the key to another one in the GNOME Tweaks app. AATWS follows this key.

When you talk about "tiles", you mean those window thumbnails that AATWS can create, right? It took me a while to realize as I consider them as a monitoring tool, not as a part of workspace navigation.

If you need direct access to workspaces I'd suggest you try the 'BaBar Task Bar' extension or 'Workspaces Bar', you can even name each workspace for better orientation (you can use my 'Workspace Switcher Manager' extension to name workspaces).

**Comment by G-dH** [comment]
I was about to mention that AATWS can also sort windows by workspace and as always I tested the feature first. And I found a bug in initial selection for this sorting mode, so I fixed it. Thanks to you :)
