### ISSUE TITLE
Switching workspaces is broken from Overview

### ISSUE THREAD

**Issue by marcinjahn** [G-dH/advanced-alttab-window-switcher#25]
I noticed that enabling the AATWS extension breaks the functionality of switching workspaces from Overview.
Here's what I mean:

## Without the extension

I  open Gnome Overview (Ctrl + Space in my case). Then, I can use Alt+Tab to switch to the next workspace (I configured this shortcut in Gnome Settings).
I can switch between workspaces without any issue.

## With the extension enabled

I  open Gnome Overview (Ctrl + Space in my case). Then, when I use Alt+Tab, the following happens:

1. If the next workspace does not have any windows open, I switch to the next workspace, as I'd expect
2. If the next workspace has any windows, I'm switched to that new workspace, and then one of the windows gets "selected". It results in exiting Gnome Overview.

**Comment by G-dH** [comment]
Thanks for the report! I don't use this option so I didn't notice.. Fixed.
