### ISSUE TITLE
How to see all windows with previews by default?

### ISSUE THREAD

**Issue by marcinjahn** [G-dH/advanced-alttab-window-switcher#26]
I would want to get the same result as in the screenshot in the readme file:

![image](https://user-images.githubusercontent.com/10273406/168839508-af436853-5718-4396-a025-dc1504bc290c.png)

Currently, what I have is App Switcher which looks pretty much the same as the default Gnome switcher. I'd like to turn it into the above. I looked through the settings, but I cannot figure out what to change. Which settings should I set?

**Comment by G-dH** [comment]
Maybe you missed this information (its also in the README):
https://github.com/G-dH/advanced-alttab-window-switcher/issues/23

**Comment by marcinjahn** [comment]
Btw, I just noticed that on your screenshot the windows have counter with value "6". How is that possible? In my case, all windows have value "1" for a counter. I'd actually expect the counter to not be even visible for windows switcher - every window represents a single window after all.

**Comment by G-dH** [comment]
It's not a window counter, it wouldn't make any sense to me, it's a workspace index ;)

**Comment by marcinjahn** [comment]
Not it makes sense :)

**Comment by arun54321** [comment]
I'm confused. how do you get window previews on alt+tab with this extension?
