### ISSUE TITLE
Hotkey combo for escape hatch to 'all apps' native switcher

### ISSUE THREAD

**Issue by drschwabe** [G-dH/advanced-alttab-window-switcher#3]
Default hotkey in Gnome is to show all apps (on all workspaces) organized by icon is ALT or CMD/WIN key + tilde

This function should be available while AATWS is open

However, it seems AATWS has a hotkey making use of tilde so to access this native 'all apps' summary you must first release the alt key and then re-press ALT and tilde (or CMD/WIN + `) 

Alternatively AATWS could implement a UI for showing a summary of all apps like that ie- by icon 
but I think the native one is fine and that would be easier to get an immediate solution to this issue.  

My UX and needs specifically is a habbit of reaching for that 'all apps' icon summary as a quick way to get to one or two apps that I typically have open but don't necessarily know or want to navigate to its specific workspace as intermediary step. Ie- slightly faster to find an app by icon in that native menu than AATWS if you have AATWS configured to group by workspace/require workspace switch.  Currently I prefer AATWS for finding not so common windows or things like terminals or browsers that have multiple windows open; would be nice to have the best of both and to switch between them seamleslly!

**Comment by G-dH** [comment]
Alt/Super+`/~ in GNOME defaults is used to switch between windows of active app. AATWS uses the `/~ hotkey to grouping windows by app and switch between those apps. I'm thinking about an option to show single app icon instead of all windows of an app and expand to windows only when selected.

**Comment by G-dH** [comment]
I just uploaded an update with the application switcher and app launcher. In the app switcher the `~/;` hotkey iterates over windows of selected application and you can use `Ctrl+;/~` to switch between window switcher and app switcher.

**Comment by G-dH** [comment]
@drschwabe Hi, do you have any comments on the current app switcher features and behavior?

**Comment by drschwabe** [comment]
It's working great, sry for late reply!
