### ISSUE TITLE
Text only settings?

### ISSUE THREAD

**Issue by dxps** [G-dH/advanced-alttab-window-switcher#32]
First of all, this is an awesome extension!
You already know this, but I wanted to express the appreciation. :blush: 

I was searching, but I couldn't figure what settings should I use to just have the "text only" version, as in your screenshot:
![image](https://user-images.githubusercontent.com/14140226/179396616-f95fc915-3155-4021-8b50-d8e38f5d484f.png)

Sorry if I missed the required combo. Tried various settings, but what I could end up is this version:
![image](https://user-images.githubusercontent.com/14140226/179396810-32f435fc-bf84-4399-847c-34e078b7f2cb.png)

For example, I would expect this to exist in _App Switcher > Appearance_. What I'm currently having there is:
![image](https://user-images.githubusercontent.com/14140226/179396742-0dc9bac6-d20a-4081-967d-3efd0f4667dc.png)

Thanks!

**Comment by G-dH** [comment]
Thanks for the feedback! I'm sorry, there is no such option in AATWS, this is a workspace switcher popup modified using my other extension [Workspace Switcher Manager](https://github.com/G-dH/workspace-switcher-manager).

**Comment by dxps** [comment]
Got it, thanks! I'll continue using this extension, of course.
Maybe you could consider adding this version to it.

Oh, forgot to mention that there's a small typo in the _Misc_ section: (Force App Switcher Include) Favoreites -> Favorites

**Comment by G-dH** [comment]
Thanks, I'll fix the typo. If you want textual window switcher, you can try extension _Switcher_ instead. Or my another extension _Overview Feature Pack_ offsers window search provider in the Overview search.

**Comment by dxps** [comment]
Appreciate the feedback! :pray: 
Yeah, that [Switcher](https://extensions.gnome.org/extension/973/switcher/) extension looks very similar with what I'm currently have as a Pop!_OS user. It's fine, but I think it has a different purpose than Alt+Tab, imo.
