### ISSUE TITLE
Pressing ALT+SHIFT+TAB doesn't show a popup

### ISSUE THREAD

**Issue by yusi1** [G-dH/advanced-alttab-window-switcher#34]
Pressing `ALT+TAB` shows a normal popup to switch between windows in the forward direction.
But pressing `ALT+SHIFT+TAB` doesn't show any popup like it would with `ALT+TAB`, and it just shows the title of what is being selected.

- Also, doing `ALT+TAB` and then `ALT+SHIFT+TAB` does show a popup like normal.
- Note: Doing `WIN+SHIFT+TAB` does show a popup.

Video:

https://user-images.githubusercontent.com/82241382/183502073-a391031f-dbe0-4ec9-b0a5-8ecdde0402c2.mp4

**Comment by G-dH** [comment]
- distro?
- shell version?
- what other extensions are enabled?

Does the issue persist if you disable all other extensions?

In a terminal, execute:

    journalctl /usr/bin/gnome-shell -fo cat

then reproduce the issue and show me the log output.

**Comment by G-dH** [comment]
Also try to install the latest GitHub version.

    git clone https://github.com/G-dH/advanced-alttab-window-switcher.git
    cd advanced-alttab-window-switcher/advanced-alt-tab@G-dH.github.com/
    make install

**Comment by yusi1** [comment]
> * distro?
> * shell version?
> * what other extensions are enabled?

Sorry for not providing that information, here's some more information:
- Distro: Void Linux
- Shell Version: 42.3.1
- Other Extensions: Tray Icons Reloaded, Vitals and Wireguard Indicator

> In a terminal, execute:
> 
> ```
> journalctl /usr/bin/gnome-shell -fo cat
> ```
> 
> then reproduce the issue and show me the log output.

Sorry, but how would I do this without using `journalctl`? My distro doesn't use SystemD.

> Does the issue persist if you disable all other extensions?

Yes.

**Comment by yusi1** [comment]
> 

Indeed, the issue does not appear when using the Github version.

**Comment by yusi1** [comment]
> Also try to install the latest GitHub version.
> 
> ```
> git clone https://github.com/G-dH/advanced-alttab-window-switcher.git
> cd advanced-alttab-window-switcher/advanced-alt-tab@G-dH.github.com/
> make install
> ```

Indeed, the issue does not appear when using the Github version.

**Comment by G-dH** [comment]
Thanks for the feedback, the issue was related to the added Show Apps Icon.

**Comment by yusi1** [comment]
> Thanks for the feedback, the issue was related to the added Show Apps Icon.

No problem, I'm glad that you found the culprit.
