### ISSUE TITLE
Picture-in-picture windows

### ISSUE THREAD

**Issue by benintech** [G-dH/advanced-alttab-window-switcher#35]
I don't know if they are supposed to be shown, but Firefox's picture-in-picture windows are not in the list :

In the app switcher I have 4 Firefox windows :
![ff-picture-in-picture_4-windows](https://user-images.githubusercontent.com/5140169/184182261-b9bfe732-0946-4dbe-8d9d-b13cf8cfb440.png)
Yet only 3 are shown in the applications's window switcher (the fourth being the Firefox's picture-in-picture window) :
![ff-picture-in-picture_3-windows](https://user-images.githubusercontent.com/5140169/184182527-40b72f8f-e3c6-44d5-bb97-647e28c2f4b2.png)

**Comment by G-dH** [comment]
FF PIP windows are flagged as "SKIP TASKBAR" so they shouldn't appear in the switcher. The AATWS window counter doesn't filter windows registered to an app, it's a bug.
