### ISSUE TITLE
[feature request] Soft wraps in app switcher

### ISSUE THREAD

**Issue by joihn** [G-dH/advanced-alttab-window-switcher#37]
Thanks for this great tool !

I often have many apps opened, such that in the app swicher (alt+tab menu), the line is too long for my screen and goes out of it (then I don't see all my opened apps at once :crying_cat_face:  )

I would love to have soft-wrap, aka multiple rows when one row is not enough :smiley:

**Comment by G-dH** [comment]
I'm sorry, AATWS will stick with a single row list. The only improvement in this regard could be adaptive icon size.
If you have so many apps open, tabbing between them is ineffective anyway, in this case you can use 'type to search' feature (usually only the first character of the app name is needed) and/or spread your apps across workspaces and set the AATWS filter accordingly.

**Comment by joihn** [comment]
okay, thanks
