### ISSUE TITLE
[FEATURE] show search results on multiple lines

### ISSUE THREAD

**Issue by benintech** [G-dH/advanced-alttab-window-switcher#38]
I increased "Max Number of Search Results" to 24 :

![only-1-line](https://user-images.githubusercontent.com/5140169/185928842-e140d161-19d6-4cea-83d3-2c0ded341a86.png)

It would be great if there was as setting to show the results in a grid (2x12 or 3x8 would be great here).

**Comment by G-dH** [comment]
I'm sorry, AATWS will stay in one row, its purpose is quick navigation, not starring at icons ;)
