### ISSUE TITLE
[FEATURE] Window Switcher : Ability to just use Icons (no preview)

### ISSUE THREAD

**Issue by mbousq** [G-dH/advanced-alttab-window-switcher#39]
**Is your feature request related to a problem? Please describe.**
I always found previews more confusing than anything else :D. I usually locate the icon to choose which tab I want.

**Describe the solution you'd like**
Be able to set the preview as low as 0 pixel so that I can just have the app icon (at moment min is 16 pixel). 

Amazing extension !

**Comment by G-dH** [comment]
If you're not using multiple windows of a single app, why not just replace the window switcher with an app switcher?

**Comment by mbousq** [comment]
I actually do. When I have multiple windows, I mostly use the icons and titles to know which window I am interested in. I find that the previews add too much clutter/confusing as in my case they are too similar (white background with some text on it).  I also combine this with the "show selected window" when alt-tabing, that could be interpreted as "full scale preview". Just some thoughts !

**Comment by G-dH** [comment]
The spin button has limitation set to 16 but you can set 0 using the `dconf Editor`.
`/org/gnome/shell/extensions/advanced-alt-tab-window-switcher/win-switcher-popup-preview-size`

**Comment by mbousq** [comment]
Many thanks, it worked :)

**Comment by G-dH** [comment]
I will change the lower limit to 0 because the truth is that no preview is better than the 16px one :)

**Comment by mbousq** [comment]
haha totally agree :)
