### ISSUE TITLE
Option to show icon instead of thumbnail for DND  

### ISSUE THREAD

**Issue by drschwabe** [G-dH/advanced-alttab-window-switcher#4]
The DND feature is really cool !   

On this topic, another feature request / idea:
 
For some windows, like 'favorite' apps that you have always open maybe Thunderbird or a note taking app it might be more intuiitve to have just a floating icon - but with all the same features of the current thumbnail versions (resizable, draggable, pins to every workspace, etc) 

It might be cool if there was a hotkey / mouseclick combo that could toggle said thumbnail to this icon format (ideally taking up perhaps the same dimensions ie- with the icon centered such that there is no distracting change of size on switch)

**Comment by G-dH** [comment]
This shouldn't be a problem.

**Comment by G-dH** [comment]
Already in repository, Ctrl+Primary button switches between preview and icon.

**Comment by drschwabe** [comment]
Hey works pretty good!  I think there could be an improvement visually to help make icon size consistent but probably this feedback would be better communicated with an actual mock visualization so I'll close this issue and perhaps open again if I get around to making said mock.
