### ISSUE TITLE
Activities Overview is not available anymore since v20 for Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by frederikb96** [G-dH/advanced-alttab-window-switcher#40]
**Describe the bug**
Since the update to v20, when pressing the Super button, the activities window is not shown anymore. Instead it directly shows the possibility to switch between apps.

Behavior in previous version / here with v20 disabled:
![Expected behavior with v20 disabled](https://user-images.githubusercontent.com/83548283/189485479-f5471000-fd4d-45c0-8dcb-60e6342047a0.png)

Real behavior with v20 enabled:
![Instead this is shown](https://user-images.githubusercontent.com/83548283/189485609-cf9d702d-61b8-4940-ba4e-8bf941efcfda.jpg)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 or 22.04]
 - Version of the extension [20]
 - Source of installation [Gnome Extensions]

**Comment by G-dH** [comment]
`Settings` -> `Common` -> `System Integration` -> `System Super Key Action` -> `Default`

**Comment by frederikb96** [comment]
Thanks and sorry for the unnecessary issue
