### ISSUE TITLE
[BUG] Options for minimized windows have no effect

### ISSUE THREAD

**Issue by rafalglowacz** [G-dH/advanced-alttab-window-switcher#41]
**Describe the bug**

I've just installed Fedora and enabled this extension. I went to the options and disabled _Window Switcher > Minimized Windows Last_ but it doesn't work. Minimized windows are still moved to the end of the list. 

I decided to check the other options related to minimized windows and they seem to have no effect either. I have "Distinguish Minimized Windows" enabled but minimized windows look the same as others, also "Skip Minimized Windows" doesn't do anything if I try it.

Other settings (not related to minimized windows) work fine, for instance I changed _Common > Placement_ to Center, no issues.

**Desktop**
 - OS: Fedora Linux 36 (Workstation Edition)
 - Gnome 42.4 - **fairly new release**, maybe this is the culprit?
 - Wayland or Xorg, same behavior
 - Version of the extension 20
 - Source of installation: https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/

**Comment by G-dH** [comment]
Are you sure you're using window switcher and not app switcher which is default in Fedora?

**Comment by rafalglowacz** [comment]
I've made a short video: https://youtu.be/yfYbMM9LGRM

**Comment by rafalglowacz** [comment]
You are correct. Sorry for the confusion, I didn't realize I was looking at a different switcher.
