### ISSUE TITLE
Disable App Switcher (keeping Window Switcher) or be able to rotate it 90 degrees

### ISSUE THREAD

**Issue by hvico** [G-dH/advanced-alttab-window-switcher#42]
I have a multi-monitor setup. I like the Window Switcher feature very much, but the App Switcher seems to interfere with my setup. The App Switcher is shown in the primary (first monitor), which has another one below it. When I try to move the mouse to the monitor below the App Switcher appears and prevents me to access that other screen (it acts like a sticky border).

I already have a sort of dock placed vertically and would like to completily disable the App Switcher and keep the Windows Switcher.

**Describe the solution you'd like**
No clear option to disable the App Switcher or change its location / placement.

**Describe alternatives you've considered**
Being able to rotate the App Switcher to place it vertically, to replace my current Dock.

**Additional context**
I have a 5 screen setup. Primary (top left), two others to its right, and a couple o screens below the first and the third. The App Switcher prevents me to move from the primary (top left) to the one below it.

**Comment by G-dH** [comment]
You need to set option `Hot Edge Position` on `Common` page of `Settings` window to `Disable`.  I've set this as default to draw users' attention to this new feature. AATWS cannot work in vertical orientation, yet.

**Comment by hvico** [comment]
Thank you, that worked! 

Yes, this new behaviour started after a recent update, now I realize that.

**Comment by G-dH** [comment]
Thanks for the feedback. If you find any other inconvenience or have any suggestion, especially related to your multi-monitor setup, let me know.
