### ISSUE TITLE
[BUG] The extension breaks Gnome Shell sloppy focus and raise window delay

### ISSUE THREAD

**Issue by tukanos** [G-dH/advanced-alttab-window-switcher#44]
**Describe the bug**
After lengthy debugging and help of FeRD (Frank Dana) [@ferdnyc](https://gitlab.gnome.org/ferdnyc) - the original ticket is [here](https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/409). I have found out that AATWS - Advanced Alt-Tab Window Switcher breaks the Gnome Shell's sloppy focus (now called differently) and raise window delay functionality. 

The functionality does not work at all.  I'm reporting it as one issue as it seems these two issues are closely connected.  If you want to create 2 issues I can.

The GNOME Shell version is  **42.4**

**To Reproduce**
I) Steps to reproduce the behavior:
1. Switch on the AATWS
2. Go to the Gnome Tweaks window and the Windows tab
3. There select `Focus on Hover` OR `Secondary-Click`
4. Raise Windows When Focused is turned on
5. Both these functionalities do not work correctly afterwards.  The work the same way for both but the difference should be:
5a) **Focus on Hover** - _Window is focused when hovered with pointer.  Windows remain focused when the desktop is hovered_
5b) **Secondary-Click** - Window is focused when hovered with pointer. Hovering the desktop removes focus from the previous window.

II) The delay in the window focus
1. Switch on the AATWS
2. in `dconf-editor`, navigate to `/org/gnome/desktop/wm/preferences/auto-raise-delay`
3. change the default value to, for example, 2000ms
4. Test the window raise delay.  The windows are still raised immediately ignoring the delay value

**Expected behavior**
**Focus on Hover** - _Window is focused when hovered with pointer.  Windows remain focused when the desktop is hovered_
**Secondary-Click** - Window is focused when hovered with pointer. Hovering the desktop removes focus from the previous window.

For the window raise delay to be obeyed.

**Desktop (please complete the following information):**
-- System Information:
> Debian Release: bookworm/sid
>   APT prefers testing
>   APT policy: (500, 'testing')
> Architecture: amd64 (x86_64)
> Foreign Architectures: i386

> Kernel: Linux 5.19.0-1-amd64 (SMP w/8 CPU threads; PREEMPT)
> Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE=en_US:en
> Shell: /bin/sh linked to /usr/bin/dash
> Init: systemd (via /run/systemd/system)
> LSM: AppArmor: enabled
> 

 - Version of the extension: 20
 - Source of installation I think it was GitHub but not 100% sure.

**Comment by G-dH** [comment]
Thanks for the report. The only AATWS option that affects window manager behavior is `Always Activate Focused Window` on the `Misc` tab of the Settings window and if it's enabled you had to do it yourself. When it comes to the `Secondary-Click` focus issue, it never removes focus from a window when the pointer hovers over a Desktop, on any of my systems (Ubuntu, Fedora, no DING), no mater whether the AATWS is enabled.

**Comment by tukanos** [comment]
I see, I'm sure I have enabled it myself.  At the beginning when using the plugin I was playing around with the settings and forgot about it.

Thank you for clearing up the issue.  After unchecking the "hack" option it started working as it should.

**Comment by tukanos** [comment]
> I've fixed the issue so now the option shouldn't rise windows.

Thank you for the fix!
