### ISSUE TITLE
[BUG] The minimum delay before the switcher pops up is actually longer than set in preferences

### ISSUE THREAD

**Issue by Jkoutsoumpas** [G-dH/advanced-alttab-window-switcher#45]
**Describe the bug**
In settings under "Common", the Delay Showing Switcher numeric value does not accept anything lower than 10ms. Therefore there is no way to **completely disable** any artificial delay that the switcher imposes, which in its current state it is 10ms minimum.

**To Reproduce**
1. Go to Settings -> Common tab
2. Enter "0" in the Delay Showing Switcher numeric box

**Expected behavior**
The value of "0" should be accepted.

**Desktop (please complete the following information):**
 - OS: Arch 
 - Version of the extension: 20
 - Source of installation: pacman

**Comment by G-dH** [comment]
There is no way your brain can notice the 10 ms difference but it wouldn't help anyway because creating the switcher popup takes usually more time depending on your system and content of the switcher. Be sure that I'm optimizing the code for the speed of displaying the popup.

**Comment by Jkoutsoumpas** [comment]
The brain can and is capable to tell delays of 10ms, it can even do it with 1ms. Drummers are especially able to discern delays of +1ms. But please let's not argue about this and stay focus on the issue at hand.

Using Gnome 42 + Wayland + 60Hz screen + the extension "Remove Alttab Delay" (https://extensions.gnome.org/extension/2741/remove-alttab-delay-v2/) installed and enabled. Directly comparing the stock Gnome Window Switcher (alt+tab) with Advanced Alt-Tab Window Switcher (with a Delay setting of "10ms"), I can **definitely tell that there is a delay before AATWS pops up, whereas the stock alt-tab switcher comes up instantaneously** (probably within the next frame). 

If this is due to the artificial delay of +10ms that AATWS imposes, then please, disable it so it behaves the same as stock Window Switcher.

**Comment by Jkoutsoumpas** [comment]
Here is a demo, recorded with my phone at  *960* FPS, which it can record with almost 1ms resolution (i.e. can and will record if the AATWS has been displayed by the screen or not):

https://user-images.githubusercontent.com/23363445/194330494-25040bd6-dd15-4aff-8d68-317c965583d9.mp4

As you see, I very quickly press alt-tab, the window switches but no AATWS is ever been displayed, not even for 1ms.

**Comment by G-dH** [comment]
Try the latest update if it's better. The delay can be set to 0 now, but that has no real impact since the delay given by building the switcher is always longer and AATWS subtracts that time from the delay set by the user.
