### ISSUE TITLE
[BUG] "Pop-up at Mouse Pointer Position" has tiny raise around screen edge

### ISSUE THREAD

**Issue by thjderjktyrjkt** [G-dH/advanced-alttab-window-switcher#49]
**Describe the bug**
When "Pop-up at Mouse Pointer Position" is enabled, and AATWS is triggered by hot edge, AATWS doesn't pop up at the absolute edge of the screen but has a tiny raise from the screen bottom. This had caused a tiny issue for me:

- I've setup AATWS to select items with scrolling on switcher background, and mouse click on switcher background to activate selection
- I was used to triggering AATWS by dragging mouse to the edge, then use mouse wheel to select window and mouse click to bring up window
- This was ok with previous version (before you made huge changes to settings UI), but not anymore:
- AATWS now has a tiny raise from screen bottom, so that right after triggering AATWS the mouse cursor is already considered outside switcher and is subject to disappear by the "Pointer Out Timeout" settings. Also I have to change "Outside switcher" settings to align with "switcher background", but with all mouse buttons occupied I now don't have a easy way to close switcher using only mouse, apart from waiting the timeout.

**To Reproduce**
1. Enable "Pop-up at Mouse Pointer Position"
2. Use `Custom Hot Corners - Extended` extension and configure the bottom-left / bottom-right corner to trigger window switcher
3. Move your mouse to the bottom-left / bottom-right corner

**Expected behavior**
AATWS switcher should pop up at the absolute screen edge.
OR
visually stay as it is, but change the actual "switcher Background" zone to include the screen edge (where mouse cursor is at). I think this is similar to Dash to Dock (where it also has a visual raise from screen bottom, but mouse press still works at the absolute bottom edge)

**Screenshots**
![image](https://user-images.githubusercontent.com/40300931/202413563-474b3966-7166-4da8-a2bd-b59f2f981a5f.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Version of the extension: 20
 - Source of installation: extension.gnome.org

**Additional context**

**Comment by thjderjktyrjkt** [comment]
If you go the latter way please also add a comment in relevant code so others won't consider it obscured and revert it.

**Comment by thjderjktyrjkt** [comment]
Wait, is it already covered in main branch?

Did a quick explore and found this:

https://github.com/G-dH/advanced-alttab-window-switcher/blob/73c07a4b921674480e920f2b5b8f7ce09d622877/windowSwitcherPopup.js#L1347

**Comment by thjderjktyrjkt** [comment]
Also, when triggering AATWS with top-right corner, the shifting is too far from where cursor is at.
![image](https://user-images.githubusercontent.com/40300931/202422552-eabf44ff-b1b4-475d-bf86-94c89e6910e0.png)

**Comment by thjderjktyrjkt** [comment]
I think this is the part where switcher position is calculated based upon cursor position?

https://github.com/G-dH/advanced-alttab-window-switcher/blob/73c07a4b921674480e920f2b5b8f7ce09d622877/windowSwitcherPopup.js#L675

And `childNaturalHeight` / `childNaturalWidth` are the actual displayed size of switcher?

**Comment by thjderjktyrjkt** [comment]
This line calculates the vertical position of switcher:

https://github.com/G-dH/advanced-alttab-window-switcher/blob/73c07a4b921674480e920f2b5b8f7ce09d622877/windowSwitcherPopup.js#L681

~~It seems pretty good? can't find any issue here.~~ I've just realized switcher has a transparent header which is counted as part of `childNaturalHeight`. this is somehow confusing. maybe you should revert `POPUP_POSITION` if `childBox.y1` is smaller than half of screen vertical size.

**Comment by thjderjktyrjkt** [comment]
I don't understand this recursive (because i don't know about javascript):
https://github.com/G-dH/advanced-alttab-window-switcher/blob/73c07a4b921674480e920f2b5b8f7ce09d622877/switcherList.js#L144

**Comment by thjderjktyrjkt** [comment]
Changing margin to `30` fixed this issue for me.

https://github.com/G-dH/advanced-alttab-window-switcher/blob/73c07a4b921674480e920f2b5b8f7ce09d622877/windowSwitcherPopup.js#L1348

But is it related to screen scaling? perhaps you need to scale margin with screen scaling factor?

**Comment by G-dH** [comment]
Please, try the latest version:

    git clone https://github.com/G-dH/advanced-alttab-window-switcher.git
    cd advanced-alttab-window-switcher/
    make install

**Comment by thjderjktyrjkt** [comment]
this fixes the screen edge (both buttom and top), but it seems to completely ignore cursor position even if triggered by mouse.

**Comment by G-dH** [comment]
Then update also CHC-E from GitGub.

**Comment by thjderjktyrjkt** [comment]
CHC-E has some dependencies to build and i can't find them.

just curious though, any specific reason to start using `CHCE_TRIGGERED`? it seems to work despite being removed. And you had this comment:

```
this.KEYBOARD_TRIGGERED    = true; // can be set to false if mouse was used to trigger AATWS
```

maybe somthing like this would guarantee better compatibility?

```
this.POSITION_POINTER && (this.CHCE_TRIGGERED || !this.KEYBOARD_TRIGGERED)
```

**Comment by thjderjktyrjkt** [comment]
when triggered by mouse, top-left, top-right and buttom-right corners are ok.

but buttom-left seems to still not fully cover the edge position when switcher is overflowing and placement is set to Top in settings.

**Comment by thjderjktyrjkt** [comment]
and when triggered by top-right or bottom-right corner, the switcher seems to react to the mouse hover too fast, causing the selection to jump. again only an issue when switcher is overflowing.

**Comment by G-dH** [comment]
CHC-E make needs `glib-compile-resources`, which should be included in the `glib2-devel` package.

**Comment by thjderjktyrjkt** [comment]
> CHC-E make needs glib-compile-resources, which should be included in the glib2-devel package.

Thanks. now it builds and `CHCE_TRIGGERED` is `true`.

---

i dug into the reverse order thing and i still haven't figured out how to reverse mouse wheel action. but i made this change:

```javascript
    _shouldReverse() {
        if (this.KEYBOARD_TRIGGERED || !options.REVERSE_AUTO) {
            return false;
        }
        if (this._reverseOrder) {
            // ↑ Speeds up things by skipping the calculation
            return true;
        }

        let geometry = global.display.get_monitor_geometry(this._monitorIndex);
        let mousePointerX = global.get_pointer()[0];

        // ↓ Store result into '_reverseOrder'
        if (mousePointerX <= ((geometry.x + geometry.width) / 2) ) {
            this._reverseOrder = false;
            return false;
        }
        else {
            this._reverseOrder = true;
            return true;
        }
    }
```

because switcher should already reverse itself when screen is at the right half.

---

is there a better way to debug gnome extension than just `log`? currently i use this to output debug log:

```javascript
// logging disabled by default
const EXT_NAME = `[${Me.metadata.name}]`;
const DEBUGGING = true;

function dbg_log(message) {
    if (DEBUGGING) {
        log(EXT_NAME, message);
    }
}

...

        if (DEBUGGING) {
            dbg_log(`CHCE_TRIGGERED: ${this.CHCE_TRIGGERED}`);
            dbg_log(`POSITION_POINTER: ${this.POSITION_POINTER}`);
            dbg_log(`KEYBOARD_TRIGGERED: ${this.KEYBOARD_TRIGGERED}`);
        }
```

**Comment by G-dH** [comment]
> just curious though, any specific reason to start using CHCE_TRIGGERED?

Since AATWS has its own mouse trigger (Hot Edge option), situation is more complicated.

> Maybe add an option for this behavior (don't reverse selection order)? is it hard? does it deserve its own issue?

It's not hard, it's just a matter of personal preferences. Now that reflects my sense of logic.

> reverse order also reverse keyboard shortcut, so Alt + Tab selects the left item as well.

Only if !KEYBOARD_TRIGGERED and in that case you don't need the Alt. Tab selects next item, not previous.

> is there a better way to debug gnome extension than just log?

I have `journalctl /usr/bin/{gjs,gnome-shell} -fo cat` always running in one terminal window and `print/log` is my basic tool. You can also throw an error with stack trace when you need.
