### ISSUE TITLE
Conflict with Pop-shell

### ISSUE THREAD

**Issue by FlyinPancake** [G-dH/advanced-alttab-window-switcher#5]
Hi, I have been using your extension for some time, and sometimes the alt-tab menu doesn't show up. I discovered disabling pop-shell makes the problem go away and thus the alt-tab popup opens. Could you look into that? I'm running fedora 34 with gnome 40.3. The pop-shell is installed from the fedora repos, and this extension is installed from gnome.org

**Comment by G-dH** [comment]
Hi. First we need to find out if the switcher is actually called from the Shell. When you have the Pop Shell enabled and AATWS disabled, the problem goes away too?

**Comment by FlyinPancake** [comment]
Yes if I have pop-shell disabled AATWS works reliably but when I have it turned on it rarely works. I'll pull up a VM and see if the problem still occurs on a fresh fedora install

**Comment by FlyinPancake** [comment]
Just did that, and installing `gnome-shell-extension-pop-shell` from dnf and AATWS from the gnome extensions site did result in the same conflict. :disappointed: 

I'd be happy to help any way possible :smile:

**Comment by G-dH** [comment]
Well, I did a quick review of the Pop Shell source code and found that the extension modifies the core function of both window and app switchers. So when AATWS is enabled before the Pop Shell, the problem emerges. I guess that when you disable and then enable the AATWS while the Pop Shell is enabled, the problem goes away. I'll workaround this.

I'll let you know when the code is ready and you can test it before I'll send it to e.g.o.

**Comment by FlyinPancake** [comment]
Thanks for the advice, and the quick replies! I'll be fine living w/o 
pop-shell for some time :)

**Comment by G-dH** [comment]
Done. You can download the code from the repository and unpack the new files to your extension directory

    ~/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com

Then restart the Shell.

This update includes an App switcher in addition to the Window switcher, you can use system shortcuts including Alt+;/~ for switching windows of focused application, and you can switch between those modes using Ctrl+;/~. Check README.MD on the code page.

**Comment by FlyinPancake** [comment]
The issue went away thanks :smile: 

OFF: Can I set a separate keybinding to open AATWS in search mode? (to replace pop-shell run window)

**Comment by G-dH** [comment]
You can set in the AATWS preferences the Search mode as default..

**Comment by FlyinPancake** [comment]
Thanks gonna try out :)

**Comment by FlyinPancake** [comment]
And I'll close the issue since it's fixed

**Comment by G-dH** [comment]
One more thing - I now updated the code so the next release from e.g.o site will update the extension automatically, and removed debug prints. Download the code once again and replace the files. Thanks for testing.

Btw, with the _Custom Hot Corners - Extended_ extension you can trigger the switcher with different settings using a mouse or custom keyboard shortcuts and you can use the App switcher popup as a Dock launcher with app search (with repository version of CHC-E).

**Comment by FlyinPancake** [comment]
In essence this is what i'm looking for, just with KB shortcuts.
