### ISSUE TITLE
[Question] multirow feature implementation hints

### ISSUE THREAD

**Issue by joihn** [G-dH/advanced-alttab-window-switcher#50]
thanks for this cool repo :) 
I miss the "multirow" feature (https://github.com/G-dH/advanced-alttab-window-switcher/issues/37) and will try to implement it myself on a fork.
Could you please give me some "rough approximate direction" on where you think it should be implemented ? 

Thanks in advance :)

**Comment by G-dH** [comment]
You need to extend the original `SwitcherPopup.SwitcherList` class, on which the AATWS `SwitcherList` is built.

**Comment by joihn** [comment]
thanks
