### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by isapir** [G-dH/advanced-alttab-window-switcher#52]
**Is your feature request related to a problem? Please describe.**
In certain themes it is hard to see the highlighted application due to low contrast

**Describe the solution you'd like**
It would be great if users could customize the color, and more importantly the background color of the highlighted application, e.g. by entering an RGB color hex code

**Comment by isapir** [comment]
To clarify, I am talking about these styles: 
![image](https://user-images.githubusercontent.com/885907/205988459-72bc15d2-d86b-48fb-b9bc-4c087a7736f5.png)

**Comment by isapir** [comment]
Alternatively, it might just be easier to add a high-contrast theme

**Comment by G-dH** [comment]
Can you give me an example how it looks in "certain themes"?

**Comment by G-dH** [comment]
@NeuHix Your problem has nothing common with this issue, create a new one.

**Comment by NeuHix** [comment]
It's nothing have to with your extension.
I didn't just found the setting to change the invocation of your "app-switcher" from "Win+Tab" to "Win" only.

**Comment by G-dH** [comment]
Create the new issue, we can discuss it there.
