### ISSUE TITLE
[FEATURE] Open every application in new workspace on Right Click

### ISSUE THREAD

**Issue by NeuHix** [G-dH/advanced-alttab-window-switcher#54]
**Is your feature request related to a problem? Please describe.**
I use keyboard a lot and navigating workspaces through keyboard is a pain. Opening a application in the current worspace and then sending it to an empty workspace is how I do it regularly. 

**Describe the solution you'd like**
An option to open that application in a new workspace on right mouse click.

**Describe alternatives you've considered**
I have used extensions related to this but they don't exactly match the expectation. 
Like "Auto Move Windows" first makes me choose an application in its settings and opens it in a fixed workspace.

**Additional context**
I believe that more than one empty workspace itself closes, so , that when i close that application from that workspace , then that workspace becomes the "empty workspace that always stays emtpy". (that image below)
![empty workspace that always stays emtpy](https://user-images.githubusercontent.com/94163435/209314103-2bb529f6-85e5-4704-81ef-145524e04d03.png)

If you know an extension for this please link it, but this feature in your app-switcher would be a great feature.
(Or maybe it's already available and i didn't found it.)
![I couldn't activate screeshot key when using your dock](https://user-images.githubusercontent.com/94163435/209315114-e146211f-cd99-4a36-81cf-e1168b4c4119.jpg)

**Comment by G-dH** [comment]
AATWS allows you to use _Shift+End_ shortcut to switch to the last (empty) workspace, so you can launch the app here directly (_Ctrl+Enter_ for new window). You can also use _Super+End_ before you open the app switcher. AATWS also allows you to move app/window to the current workspace using a hotkey (default _X_, or _Shift+X_ if search is active) and move app/window to the new workspace next to the current one using _Ctrl+Shift+Arrow Up/Down_. Other than that in the AATWS switcher you can use _Page Up/Down_ or _Arrow Up/Down_ for switching workspaces.

**Comment by NeuHix** [comment]
Super+end   is a good shortcut. Is there a similar shortcut which uses mouse to move to last workspace ?

**Comment by G-dH** [comment]
You can use _[Custom Hot Corners - Extended](https://github.com/G-dH/custom-hot-corners-extended)_ with action _Switch to Preset Workspace_ with ws index higher than max number of workspaces you will ever use. You can assign it to hot corner/edge or mouse click/scroll on any screen corner/edge.

**Comment by G-dH** [comment]
Also, the default AATWS configuration allows you to switch workspaces using a mouse wheel and move app/window to the current ws by pressing the middle mouse button.

**Comment by NeuHix** [comment]
> the default AATWS configuration allows you to switch workspaces using a mouse wheel
I really didn't knew that. 
When I first used "Custom Hot Corners" , I found the settings difficult to understand but it did get the work done.
and it also conflicted with another extension "Hot Edge". After really missing 'hot edge' for a few days, I disabled "custom hot corners".  

Now I have again configured it and it again got the work done. And it still conflicts with 'hot edge'.  
"Hot Edge" just enables me to enter overview by sliding the mouse pointer to the bottom of screen.

But I think this can  also be done through "Custom Hot Corners" , Can you tell me how it can be done ?

**Comment by NeuHix** [comment]
You really put a lot of effort in your extensions. Just the sheer amount of features reflects your effort.

**Comment by G-dH** [comment]
Of course, you don't need the _Hot Edge_ extension if you have _CHC-E_ - choose left or right bottom corner, adjust horizontal _Hot corner barrier size_ at the bottom to the max and choose _Show Activities Overview_ as the _Hot corner_ action. You can also split the edge, set the barrier size to half the scale and assign _Show Activities Overview_  action to bottom left hot corner and _Show Application Grid_ to the bottom right hot corner. Or you can leave the barrier size on minimum and in the AATWS you can set its own Hot Edge option to open AATWS. But also CHC-E can open AATWS (section _Window/App Switcher Popups_).

**Comment by NeuHix** [comment]
All these visuals mean that i either have to click a button or scroll ,  but i just want the pinter to touch the edge and enter overview.

![ ](https://user-images.githubusercontent.com/94163435/209339340-ddd0c8ec-1cca-4eca-8e58-6213548b789d.png)

**Comment by NeuHix** [comment]
Closing.  Thanks for your "Extension Support"

**Comment by G-dH** [comment]
You know what hot corner means and how it works, right? The hot corner consists from small vertical and horizontal barriers in the corner that react on "mouse pressure". At the bottom of the settings window you have sliders that allows you to extend each barrier along the screen edge, so you can extend the horizontal barrier of the bottom left, or bottom right, or even both corners. You can set action for each Hot Corner or Ctrl+Hot Corner. And if you enable option _Make Active Coreners/Edges Visible_ on the Options page, you can see on the screen what corners are active and how they are expanded.

**Comment by G-dH** [comment]
So setting the Hot Edge extension functionality in CHC-E is as simple as this:
![Screenshot from 2022-12-23 14-39-56](https://user-images.githubusercontent.com/73719686/209345721-01a0c864-1e40-4441-b679-fabb597040c2.png)

**Comment by G-dH** [comment]
Deleted comment I responded to and you won't even let me know if you figured out how it works? That means wasted time for me.

**Comment by NeuHix** [comment]
I'm sorry.  It wasn't intended.  I thought It worked, but after logging again, it isn't.

Sliding on the left edge also activates overview, however, I intended it to "go to workspace 20" when I scroll up or down.
The bottom one was intended to activated overview.

![ ](https://user-images.githubusercontent.com/94163435/209360015-04609bb8-9ac4-4ad8-8163-b946b9e11dfd.png)

**Comment by G-dH** [comment]
We have two different types of triggers in CHC-E - the first one is the hot corner pressure barrier as I described above and the second one is clickable/scrollable. Each type of the triggers has different expansion control - hot pressure barrier has the sliders, clickable area can be expanded using the toggle buttons above the sliders, there is no need for such precise adjustment. Both can be expanded in the horizontal and vertical direction. You can expand the hot corner barrier horizontally to get the bottom hot edge, but if you also want to use mouse buttons on this "corner", you should expand the clickable area vertically and use the vertical edge for it, because otherwise it will be hard to use on the same edge as the hot trigger operates. Use the option I mentioned before to visualize all active triggers an try changing the settings, you'll see how it works.

**Comment by NeuHix** [comment]
Now I have configured everything according to my needs and YES the issue is solved.

Thanks for your time.
