### ISSUE TITLE
[FEATURE] Skip current window

### ISSUE THREAD

**Issue by atimeofday** [G-dH/advanced-alttab-window-switcher#56]
**Is your feature request related to a problem? Please describe.**
AATWS requires two tab presses to go to the next window. The first press displays the switcher with the current window highlighted. Equivalent software goes to the next window with one press of alt+tab.

**Describe the solution you'd like**
A way to toggle to the "standard" behavior would be nice.

**Describe alternatives you've considered**
I've tried a couple alternative window switchers, looked through every possible setting in AATWS, tried every way I could think of to look up how to make this work, and considered the possibility of trying to implement that change myself, but I doubt I would succeed.

**Additional context**
I'm using Pop OS. I'm not sure what other context might be relevant.

(P.S., I can make another feature request for this but I would also appreciate a setting to disable previews entirely)

**Comment by G-dH** [comment]
The initial selection in AATWS in default settings is on the second item in the list which is the previously used window, there's nothing to implement. Did you try resetting all options on the About page in the AATWS Settings window?

**Comment by atimeofday** [comment]
Stable sequence was the problem. I'm happy with it now.
