### ISSUE TITLE
Is there a way to avoid grouping?

### ISSUE THREAD

**Issue by nardev** [G-dH/advanced-alttab-window-switcher#57]
I'm not in love with multiple steps if i have to switch windows. It' pretty useless app if you have to choose group and than a particular window.

There is plenty of configs but the grouping one doesn't change anything even if "none" is chooses.

I';m i missing something? Is there a way to do that?

**Comment by G-dH** [comment]
It's in the readme on the main page as a first note and also here in another issue that I keep open to be visible for any confused user :)
https://github.com/G-dH/advanced-alttab-window-switcher/issues/23#issuecomment-1111930055

**Comment by nardev** [comment]
Than you so much, it saved the day...

Seems like gnome has some issues with the shortcuts. I had some problems with yakuake too. The system shortcut was catching the F12 however, that one was not triggering yakuake's "focus" procedure so it was opening the terminal without the ocus...
