### ISSUE TITLE
[FEATURE] add auto multiple windows focus

### ISSUE THREAD

**Issue by vladimirprieto** [G-dH/advanced-alttab-window-switcher#60]
**Is your feature request related to a problem? Please describe.**
when developing usually i use 2 windows: browser and terminal.  when moving from the editor to browser, i got to first focus on terminal window and next focus on browser window

**Describe the solution you'd like**
configure an auto focus on a second (or third) window when X window get the focus

**Describe alternatives you've considered**

**Additional context**
maybe focus on the second window is a bad term.  maybe is just "bring up" from below the second window

**Comment by G-dH** [comment]
Sorry, I don't get it at all.

**Comment by G-dH** [comment]
Closing. If you decide to explain the issue to me, feel free to reopen it.

**Comment by vladimirprieto** [comment]
i think everybody must use various applications at once, and you move from one to the others.  the last ones stay deep behind on the last recent app used list.

let's say you have 6 open apps.  1 is the more recent used, 6 is the last one.   the idea is to move to the 4th and automatically show the 4th and the 5th (or whatever other app you can configure).

hope is more clear now.

(sorry my english :@)

**Comment by G-dH** [comment]
So you want a custom grouping where activating one member means all members of the group rise, like when you activate a window of a multi-windowed application?
That's why we have workspaces..
