### ISSUE TITLE
[BUG] After Debian/Gnome update, Always Activate Focused Window option caused problems

### ISSUE THREAD

**Issue by mlncn** [G-dH/advanced-alttab-window-switcher#62]
**Describe the bug**

Frequently (esp multiwindow like Firefox?) when using Alt+Tab the window is _shown_ but not _selected_ so i have to go click it with my mouse to start to interact with it.  My computer was effectively useless to me :sob: 

**To Reproduce**

Toggling one setting at a time until finding the culprit, Always Activate Focused Window being enabled seems to have been the problem.  Disabled it and AATWS worked as expected again.

**Expected behavior**

When a window is selected, it is activated, gains focus.

**Screenshots**

Everything seems fixed with this setting *disabled*

![Advanced-Alt-Tab-Window-Switcher-was-not-working-Always-Activate-Focused-Window-was-culprit](https://user-images.githubusercontent.com/27131/222528816-f04b8a42-c0f6-4dfb-b9ad-195ccfeb0f67.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux bookworm/sid
 - Version of the extension: 22
 - Source of installation: extension.gnome.org

**Additional context**

 - Gnome Version: 43.3
 - Windowing System: Wayland

**Comment by G-dH** [comment]
Do you use different input (keyboard) settings for different windows?

**Comment by G-dH** [comment]
Seems like the wm activates windows immediately even when switching workspace, so this feature is unnecessary for GS 43+.
