### ISSUE TITLE
[BUG] Switcher won't confirm selection with non-standard shortcut

### ISSUE THREAD

**Issue by notpeelz** [G-dH/advanced-alttab-window-switcher#63]
**Describe the bug**
When changing the window/app switcher to a non-standard shortcut (e.g `Super+Q`), the switcher window no longer closes when releasing the keys. Instead, I have to manually confirm the selection by pressing enter.

**To Reproduce**
1. Open the GNOME keyboard settings
2. Click "View and Customize Shortcuts" and set "Switch windows" to `Super+Q`
3. Press `Super+Q`

**Expected behavior**
I expected the switcher to confirm the selection upon releasing the shortcut keys, just like it does when the shortcut is set to `Alt+Tab`.

**Desktop**
 - Distro: Arch
 - GNOME: 43.3 (Wayland)
 - Version of the extension: 22
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
There is a conflict with `Search Mode as Default` option, but when it's disabled it should work as you expect, and it works for me on GS 42.5 and also 43.2 and 44.beta. Only if you use shortcut to activate search input, then you can release the modifier key without closing the popup. Execute following command in the terminal, then use the switcher and check if there's any relevant output that can help with debugging.
`journalctl /usr/bin/gnome-shell -fo cat`

**Comment by notpeelz** [comment]
It happens even with `Search Mode as Default` disabled. I forgot to mention I have `super` remapped to `caps`, using these xkb settings:
```
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:hyper']"
```
The problem occurs when `caps+q` is pressed. `super+q` works as expected.

**Comment by G-dH** [comment]
Fixed, hopefully without collateral damage :) Available in the repository.

**Comment by notpeelz** [comment]
Thanks. That did the trick :)
