### ISSUE TITLE
[FEATURE] Set Window mode as default

### ISSUE THREAD

**Issue by backspacestud** [G-dH/advanced-alttab-window-switcher#64]
Set window mode as default instead of app mode. If there is already a way to do this it is too complicated or hard to get to so an easier way would be nice. Thank you.

**Comment by G-dH** [comment]
I have this info everywhere - in the description on e.g.o, in the README, in issues...
https://github.com/G-dH/advanced-alttab-window-switcher/issues/23#issuecomment-1111930055

**Comment by backspacestud** [comment]
true, but a toggle would be nice as a feature and it is hard to find on the app alone. but i see that it is everywhere now thank you for the quick response.

**Comment by G-dH** [comment]
Sorry, I don't understand your feature request. You can switch between app/window modes when the switcher popup is open, but if you want AATWS to act like a window switcher when using the app switcher shortcut, it doesn't make sense to me.
