### ISSUE TITLE
[BUG] GNOME UI restart after trying to drag app window from app switcher

### ISSUE THREAD

**Issue by enesizgi** [G-dH/advanced-alttab-window-switcher#66]
**Describe the bug**
GNOME UI is restarting after doing some actions with tab switcher.

**To Reproduce**
1- Select an app from app switcher.
2- Click on the app to show windows.
3- Press on one window and drag that window.

**Expected behavior**
UI should not crash.

**Screenshots**

https://user-images.githubusercontent.com/45923323/230485349-34f2724e-7fee-4365-9844-3136b80707cf.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora 36] endeavouros 2022.12.17
 - Version of the extension [e.g. 17] 24
 - Source of installation [e.g. extension.gnome.org, GitHub] extension.gnome.org
 - Gnome Version: 43.4

**Additional context**
I am using X11 window management.

**Comment by G-dH** [comment]
AATWS doesn't support DND, so it should just react on the button press by activating the window and close. The rest shouldn't be affected by the AATWS.
Do you see any relevant info in the log?
```
journalctl /usr/bin/gnome-shell -fo cat
```
then reproduce the issue and check the output.

**Comment by enesizgi** [comment]
![image](https://user-images.githubusercontent.com/45923323/230491759-7eb67f87-a1cc-4265-8e41-109842cb3df0.png)

This is output after reproducing the bug.

**Comment by G-dH** [comment]
I'm unable to reproduce this bug. Does disabling workspace thumbnails make any difference?

**Comment by G-dH** [comment]
Btw, I'm sure the log isn't complete, those few lines are related to the restart, not the cause of the restart.

**Comment by enesizgi** [comment]
> Btw, I'm sure the log isn't complete, those few lines are related to the restart, not the cause of the restart.

st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
st_adjustment_get_values: assertion 'ST_IS_ADJUSTMENT (adjustment)' failed
st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
st_adjustment_get_values: assertion 'ST_IS_ADJUSTMENT (adjustment)' failed
st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
st_scroll_bar_get_adjustment: assertion 'ST_IS_SCROLL_BAR (bar)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
st_adjustment_get_values: assertion 'ST_IS_ADJUSTMENT (adjustment)' failed
Running GNOME Shell (using mutter 43.4) as a X11 window and compositing manager
ATK Bridge is disabled but a11y has already been enabled.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 3
Telepathy is not available, chat integration will be disabled.
[x11gestures@joseexposito.github.io] Extension enabled
[x11gestures@joseexposito.github.io] Building entry point for GNOME Shell 43.4
[x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
[x11gestures@joseexposito.github.io] Hooking global switch desktop gestures
[x11gestures@joseexposito.github.io] Creating a new SwipeTracker40
[x11gestures@joseexposito.github.io] Connecting Touchégg client signals
[x11gestures@joseexposito.github.io] Hooking global activities/overview gestures
[x11gestures@joseexposito.github.io] Creating a new SwipeTracker40
[x11gestures@joseexposito.github.io] Connecting Touchégg client signals
[x11gestures@joseexposito.github.io] Hooking activities view switch desktop gestures
[x11gestures@joseexposito.github.io] Creating a new SwipeTracker40
[x11gestures@joseexposito.github.io] Connecting Touchégg client signals
JS ERROR: Could not load extension clipboard-indicator@tudmotu.com: Error: Missing metadata.json
createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:300:19
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:628:34
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:28:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:612:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:659:14
init@resource:///org/gnome/shell/ui/extensionSystem.js:57:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:309:22
start@resource:///org/gnome/shell/ui/main.js:186:5
@resource:///org/gnome/shell/ui/init.js:6:17

Extension gsconnect@andyholmes.github.io already installed in /home/enes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io. /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io will not be loaded
Could not issue 'GetUnit' systemd call
st_widget_get_theme_node called on the widget [0x562b419c1df0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a42420 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a62500 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a72fe0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b419c22e0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a47ab0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a90980 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41aa1310 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41a95cc0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41aab860 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41ac2070 StLabel.monospace:insensitive ("100%")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x562b41ad39d0 StLabel.monospace:insensitive ("100%")] which is not in the stage.
Error loading calendars: Error calling StartServiceByName for org.gnome.Shell.CalendarServer: Process org.gnome.Shell.CalendarServer exited with status 127
[x11gestures@joseexposito.github.io] Connection with Touchégg established
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
AATWS - Advanced Alt-Tab Window Switcher: enabled
Could not create transient scope for PID 134128: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134128 does not exist.
Could not create transient scope for PID 134129: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134129 does not exist.
Could not create transient scope for PID 134130: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134130 does not exist.
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Could not create transient scope for PID 134185: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134185 does not exist.
Could not create transient scope for PID 134186: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134186 does not exist.
Could not create transient scope for PID 134187: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 134187 does not exist.
Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesDisplay>:0x562b40c44b40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesView>:0x562b428a0920] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspace_Workspace>:0x562b428a5780] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428a9b70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x562b428a4200] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428b1ef0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x562b428abe10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x562b428ae6f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x562b428bda40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428be2a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x562b428bee30] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x562b428c0960] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x562b428d2b50] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428d3570] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x562b428d4090] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x562b428d5af0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x562b428dd150] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428ddb70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x562b428de690] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x562b428e00f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x562b428e7630] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x562b428e8040] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x562b428e8b60] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x562b428ea5d0] is on because it needs an allocation.
GNOME Shell started at Fri Apr 07 2023 00:20:41 GMT+0300 (GMT+03:00)
Registering session with GDM
JS ERROR: TypeError: malformed UTF-8 character sequence at offset 1

**Comment by enesizgi** [comment]
> I'm unable to reproduce this bug. Does disabling workspace thumbnails make any difference?

Nope, it didn't help.

**Comment by enesizgi** [comment]
I think it is related to this extension I am using: https://github.com/hardpixel/unite-shell

I disabled this extension and couldn't replicate this anymore. Sorry to bother you.

**Comment by G-dH** [comment]
Still nothing relevant to the AATWS or the crash, the relevant log must be older than this. Also disable all other extensions and try to reproduce the issue on a default Shell.

**Comment by G-dH** [comment]
?

**Comment by G-dH** [comment]
Oh, I missed your last comment.
