### ISSUE TITLE
[BUG] "Activate" in Primary Click of App Switcher Not Working

### ISSUE THREAD

**Issue by NeuHix** [G-dH/advanced-alttab-window-switcher#68]
**Describe the bug**
Setting the "Primary Click on Item" of App Switcher of Mouse Section to "Activate". Does not works.  

**To Reproduce**
1. Go to Mouse Section
2. Scroll down to App Switcher
3. Change Primary Click to "Activate"
4. Togge App Switcher
5. Left Click on any icon
6. Nothing Happens 

**Expected behavior**
Activate that application when left clicked on its icon in the app switcher.

**Screenshots**
I was thinking of recording this behaviour, but incase my mouse is faulty, (which i have verified, its not, it works everywhere) ,
A software which would display my key presses would be required. I didn't found anyone that works on my system.
I would attach a recording here once I find a software that works on my system.

**Desktop :**
 - OS: Fedora 38 Workstation [GNOME 44]
 - Version of the extension : 24
 - Source of installation : extension.gnome.org

**Additional context**
However, operating the app switcher through keyboard works. I mean, I can activate the application by pressing "enter".

**Comment by G-dH** [comment]
Thanks for the report, something is blocking the event in 44, I'll try to fix it today.

**Comment by G-dH** [comment]
Should be fixed in the repository, let me know if it's OK and I release it on e.g.o.

**Comment by NeuHix** [comment]
I removed the extension. And installed it manually thorugh downloading the zip file. Turned it on. Clicked Settings. And Got this.

![image](https://user-images.githubusercontent.com/94163435/236681040-e78b4849-cf94-4cb1-8d53-fd1bc96701f9.png)


The settings of extension advanced-alt-tab@G-dH.github.com had an error:
```
GLib.FileError: Failed to open file “/home/arctrus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:228:31
Options@/home/arctrus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/settings.js:111:42
init@/home/arctrus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/prefs.js:68:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:25
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
Maybe I tampered with the folder ?

**Comment by NeuHix** [comment]
Again, after removing it, i installed it through 'git clone' , renamed the folder to "advanced-alt-tab@G-dH.github.com" , 
restared my computer , opened extension's settings, SAME ERROR.

**Comment by G-dH** [comment]
```
git clone https://github.com/G-dH/advanced-alttab-window-switcher.git
cd advanced-alttab-window-switcher/
make install
```

**Comment by NeuHix** [comment]
Okay. It works. thanks. 
Sorry I didn't know that I had to `make install`.
You can close this issue.
