### ISSUE TITLE
[BUG] Freeze of window switcher when putting window on new WS

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/advanced-alttab-window-switcher#69]
**Describe the bug**
The window switcher (activated via mouse by using an edge with the CHC extension) will freeze, i.e. still be visible, but not allow further interaction when a window is pulled onto a new work space by using the integrated functionality (in my case right click on desktop of new WS with the desired window selected).
When moving the mouse away from the window switcher it will close, however, and then works normally again.
Note that the bug occurs quite often, but not always.

**To Reproduce**
1. Open some windows
2. Use AATWS to switch to different WS (scrolling in border area with my settings)
3. Mouse over desired window to select it
4. Mouse over Desktop and right click (my settings) to bring window to current WS
5. Mouse over window switcher again to continue interacting (e.g. bring next window to current WS) and notice that it froze.

**Expected behavior**
No freeze...

**Desktop (please complete the following information):**
 - OS: Fedora 38 (did not have this issue on Fedora 36 IIRC)
 - Version of the extension: 24
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
Add some log please, if any. Execute `journalctl /usr/bin/gnome-shell -f` in the terminal and look at the output when the bug occurs.

**Comment by UndeadDevel** [comment]
Sure, here you go (let me know if there is a better way to post logs):

`May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_ui_switcherPopup_SwitcherButton (0x55747f1a9b50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2ce010 b   resource:///org/gnome/shell/ui/switcherPopup.js:566 (296a5870dfb0 @ 109)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:582 (296a5870e060 @ 53)
May 07 15:35:22 domainname gnome-shell[34774]: #2   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #4   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2ce010 b   resource:///org/gnome/shell/ui/switcherPopup.js:566 (296a5870dfb0 @ 109)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:582 (296a5870e060 @ 53)
May 07 15:35:22 domainname gnome-shell[34774]: #2   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #4   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2ce010 b   resource:///org/gnome/shell/ui/switcherPopup.js:566 (296a5870dfb0 @ 109)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:582 (296a5870e060 @ 53)
May 07 15:35:22 domainname gnome-shell[34774]: #2   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_ui_switcherPopup_SwitcherButton (0x55747f4130e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: #4   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2ce010 b   resource:///org/gnome/shell/ui/switcherPopup.js:566 (296a5870dfb0 @ 109)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:582 (296a5870e060 @ 53)
May 07 15:35:22 domainname gnome-shell[34774]: #2   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #4   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:583 (296a5870e060 @ 220)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:22 domainname gnome-shell[34774]: #2   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2cf110 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:922 (8c8738efc40 @ 203)
May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_ui_switcherPopup_SwitcherButton (0x55747f7baa80), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:895 (8c8738efbf0 @ 2945)
May 07 15:35:22 domainname gnome-shell[34774]: #2   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:22 domainname gnome-shell[34774]: #0   7ffd2d2cf110 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:923 (8c8738efc40 @ 371)
May 07 15:35:22 domainname gnome-shell[34774]: #1   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:895 (8c8738efbf0 @ 2945)
May 07 15:35:22 domainname gnome-shell[34774]: #2   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:22 domainname gnome-shell[34774]: #3   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_ui_switcherPopup_SwitcherButton (0x55747c0cc3c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: Object St.BoxLayout (0x55747cb428f0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_src_switcherItems_WindowIcon (0x55747cad3f80), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:22 domainname gnome-shell[34774]: Object .Gjs_src_switcherItems_WindowIcon (0x55747cad3f80), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. 
May 07 15:35:23 domainname gnome-shell[34774]: Object .Gjs_ui_switcherPopup_SwitcherButton (0x55747cad9740), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
May 07 15:35:23 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:23 domainname gnome-shell[34774]: #0   7ffd2d2ce010 b   resource:///org/gnome/shell/ui/switcherPopup.js:566 (296a5870dfb0 @ 109)
May 07 15:35:23 domainname gnome-shell[34774]: #1   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:582 (296a5870e060 @ 53)
May 07 15:35:23 domainname gnome-shell[34774]: #2   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:23 domainname gnome-shell[34774]: #3   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:23 domainname gnome-shell[34774]: #4   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)
May 07 15:35:23 domainname gnome-shell[34774]: == Stack trace for context 0x55747a787980 ==
May 07 15:35:23 domainname gnome-shell[34774]: #0   7ffd2d2ce0f0 b   resource:///org/gnome/shell/ui/switcherPopup.js:583 (296a5870e060 @ 220)
May 07 15:35:23 domainname gnome-shell[34774]: #1   7ffd2d2cf260 b   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:821 (8c8738efbf0 @ 487)
May 07 15:35:23 domainname gnome-shell[34774]: Object St.BoxLayout (0x55747ca1f9c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
May 07 15:35:23 domainname gnome-shell[34774]: #2   55747f40bad0 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:463 (8c8738ef6a0 @ 2085)
May 07 15:35:23 domainname gnome-shell[34774]: #3   55747f40ba28 i   /home/username/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:316 (8c8738ef600 @ 33)`

**Comment by UndeadDevel** [comment]
Maybe this is better:
![Screenshot from 2023-05-07 15-48-08](https://user-images.githubusercontent.com/30495439/236681661-c845a62a-0d52-4e0b-9c78-6d1bfb233aaf.png)

**Comment by G-dH** [comment]
Thanks, just use ``` for code/log blocks. Yeah, I know about this mess, I'm working on it..
