### ISSUE TITLE
Merge dev into main

### ISSUE THREAD

**Issue by aniketfuryrocks** [G-dH/advanced-alttab-window-switcher#7]
gnome 41 support

**Comment by G-dH** [comment]
It sounds like an order from a boss ;) New version will be available on e.g.o when I decide it's ready. This week, hopefully...

**Comment by aniketfuryrocks** [comment]
> It sounds like an order from a boss ;) The new version will be available on e.g.o when I decide it's ready. This week, hopefully...

My bad, I just wanted to update the metadata to support gnome 41. I came here to make a pull request for the same. Found u already updated it in the dev branch therefore I opened this issue. 🙏

**Comment by G-dH** [comment]
If you want to help, you could test the latest dev branch version and tell me what you think about it ;)

**Comment by G-dH** [comment]
So now it's merged and also available on e.g.o
