### ISSUE TITLE
[BUG] App launcher functionality when no window is open doesn't work again

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/advanced-alttab-window-switcher#70]
**Describe the bug**
The AATWS can display app icons as a launcher when no windows are open (this is how I've set it). However, clicking on the icons doesn't do anything.
Note that it used to not work last year for some time, when I was using Fedora 36; then it was updated (I don't remember which update, sorry) and it worked and now I've upgraded Fedora to 38 and it doesn't work again.

**To Reproduce**
1. Close all windows and set AATWS to be an app launcher in such a scenario
2. Try to launch an app with it (doesn't work)

**Expected behavior**
It should launch the app.

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Version of the extension: 24
 - Source of installation extension.gnome.org

**Comment by G-dH** [comment]
Thanks for the report, this issue seems like duplicate of #68, primary click doesn't work at all on GS 44.

**Comment by UndeadDevel** [comment]
You might be right! Primary click works for me in "window switcher mode" but not for the app switcher.

**Comment by G-dH** [comment]
Should be fixed in the repository, let me know if it's OK and I release it on e.g.o.

**Comment by UndeadDevel** [comment]
Can confirm fixed, thank you! 
Closing...
