### ISSUE TITLE
[BUG] When all windows are minimised, switching windows once opens the second window in the list, not the first

### ISSUE THREAD

**Issue by mkidson** [G-dH/advanced-alttab-window-switcher#71]
**Describe the bug**
I'm not sure if this is intended behaviour but to me it seems to not be doing what I expect. If I have 2 windows, both minimised so I'm looking at the desktop, and press Alt+Tab (can't remember if this is the default binding but for me this is switching windows) then the window switcher highlights the second window in the list. I would expect it to open the first in the list, which for me is the most recently opened window but I know that differs and I think this behaviour is wrong regardless of the ordering you choose.

**To Reproduce**
1. Have two windows open, then minimise them both.
2. Press Alt+Tab (or whatever you use to switch windows, not applications)
3. Second window in the list is highlighted and gets switched to.

**Expected behavior**
As mentioned before, I expect the first window in the list to be opened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Version of the extension: 24
 - Source of installation: extension.gnome.org

Again, this may be intended behaviour, so if it is could you point me to a way to change it to the behaviour I expect?

Thanks

**Comment by G-dH** [comment]
Thanks, I'll fix it.
