### ISSUE TITLE
[FEATURE] Show always (fixed dock mode) 

### ISSUE THREAD

**Issue by drschwabe** [G-dH/advanced-alttab-window-switcher#73]
Would like to experiment with AAWS as a fixed dock.  I'm currently using Dash to Dock + AAWS simeoultaneously but feel that I could probably use just AAWS if it had an "Show always" option to keep it open (ie- you don't have to press ALT TAB to view the apps).  Or perhaps you could call this Fixed dock mode. 

(context: efficiency/convenience - I am finding these days I want to see what windows are open on a given workspace without the extra mental effort to remember what I have on a given workspace, and without having the extra physical work to hit the extra hotkey or move mouse over) 

Just thinking aloud, for this to work perhaps all hotkeys need be muted - so you would render the AAWS row but not register any hotkeys unless ALT-Tab (or whatever user has setup for the shortcut) which 'activates' its functionality. 

And then when at rest it just behaves lilke a normal app dock so when you click an item it will bring up that window.  

ps - Dash to Dock's version of this is available simply by disabling its "Intelligent autohide" feature.  
When disabled, there is a suble but important detail in that apps will not maximize to the full screen height (unless fullscreen) to accommodate for the height of the dock.   So this would be a nice-to-have feature as well ie- to prevent AAWS Fixed Mode from overlapping maximized apps. 

pps - another reason I suggest this here is that they D2D seems not as active / quick as your development; the main issue I have with their dock is this one - which with my proposed feature here would resolve (since AAWS already has feature to just show windows): 

https://github.com/micheleg/dash-to-dock/issues/108

The default  ie- App Icons vs Windows could be decided with whatever mode was left on during the last Alt Tab and that would then persist in fixed mode.

**Comment by G-dH** [comment]
Thanks for suggestion, but this is too far from the original concept and the extension is already complex enough.

ps - AATWS works as a modal window that grabs all input (like popup menu), there is no need to register hotkeys as global shortcuts, all keyboard and mouse input events go to AATWS when it's on screen.

**Comment by drschwabe** [comment]
That's fair!  

And you explain how contextual input would be not so trivial; additional 'modes' would certainly complicate things.
