### ISSUE TITLE
Window key opens activities-oveview and app-swither BOTH.

### ISSUE THREAD

**Issue by NeuHix** [G-dH/advanced-alttab-window-switcher#74]
**Describe the bug**
I've set the window key to open the app-switcher of this extension.
But today, pressing it opens the activities-overview and the app-swither both.

**Expected behavior**
Open the app-swither only.

**Screenshots**
[Screencast from 2023-08-12 12-02-33.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/94163435/48320961-8346-4ef7-9814-d9b278840947)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Version of the extension: 26
 - Source of installation: extensions.gnome.org

**Additional context**
I know this isn't a problem with the extension. But please help me I tried many soltions off the internet but none worked.

**Comment by G-dH** [comment]
Probably another extension replacing the default overlay-key connection.

**Comment by NeuHix** [comment]
Thanks! I found it.
![image](https://github.com/G-dH/advanced-alttab-window-switcher/assets/94163435/2b708e98-af4c-4860-8d6b-63b495356205)
I had turned on the "disable overlay key" here. 
I turned it off. And now it's working as before.
