### ISSUE TITLE
[FEATURE] Automatic filter switching in single app mode

### ISSUE THREAD

**Issue by ces42** [G-dH/advanced-alttab-window-switcher#79]
**Is your feature request related to a problem? Please describe.**
I have AATWS set to only show windows on the current monitor by default. Sometimes I one window of the same application on each monitor, and I'd like to be able to quickly switch between them by pressing `alt+backtick`. Currently that only show a single window in the switcher. This feels kind of silly. Why would I ever want to switch between one and the same window?

**Describe the solution you'd like**
If there list of windows that is going to be displayed with a certain filter (monitor, workspace, all) has only one window, "move the filter up one step" until there's more than one window (or we've hit all).

**Comment by G-dH** [comment]
Added suggested behavior and fixed manual filter switching in the single-app mode.

**Comment by ces42** [comment]
Amazing, that was so fast!

Is there a reason you're not just checking `itemList.length > 1`, regardless of whether we're in single-app mode or not?
Also can I ask what the reason for this piece of code (further down in the same function) is?
```javascript
if (this._searchEntry === null || this._searchEntry === '') {
    ... select first item if firstRun
    if (this._firstRun) {
        this._initialSelectionMode = SelectMode.FIRST;
        this._selectedIndex = 0;
    } else {
...
```
At least in my use case it would me more useful if pressing `alt+backtick` were to right away select the *other* window of the app I'm using instead.

**Comment by G-dH** [comment]
That piece of code handles several situations including search, so it's not just about the one condition. I need more time to do it right and test it.
To the first selection. The code originally handles situations where there are no windows on the current monitor or workspace so the previously used window is the first one, so that's a side effect. I quite like that the first selection stays within the the current filter setting even if the temporary filter has changed..

**Comment by ces42** [comment]
The newest version is working fine for me. The previous commit also worked fine. Works as intended and I haven't noticed any bugs. Although I commented out the lines 
```js
        this._initialSelectionMode = SelectMode.FIRST;
        this._selectedIndex = 0;
```
inside that if-statement I mentioned to get faster switching.
(I also don't use search so I don't know about that part).

**Comment by G-dH** [comment]
Thanks for the feedback!

**Comment by G-dH** [comment]
@simsilver The option is not available yet, but I've changed the behavior so it automatically switches the filter only if you press your Tab key again if there is only one item in the list. Available in the repository.

**Comment by dylanmorroll** [comment]
Hey, would like to see this as an option to turn this off if possible. I sometimes absent mindedly hit alt-tab a few times as a fidget behaviour and seeing apps from other monitors distracts me. (The life of ADHD.) If possible to disable this feature via the preferences I would appreciate it :)
