### ISSUE TITLE
Ability to remap and/or disable individual hotkeys

### ISSUE THREAD

**Issue by arngo** [G-dH/advanced-alttab-window-switcher#8]
Personally I don't find some of the hotkeys useful, so it would be nice to be able to disable/unmap them to prevent accidental activation.

**Comment by G-dH** [comment]
I'll think about it. What features are useful for you, if I may ask?

**Comment by arngo** [comment]
The ones I think are most useful to me:
- left/right - window selection
- up/down - workspace selection
- shift + arrow keys - move switcher across monitors
- space - show window
- W - close selected window
- ctrl-W - close application of selected window
- N - new window of selected application 
- C - close all windows in list belonging to the same application 
- X - move selected window to current workspace and monitor

Great extension, thanks!

**Comment by G-dH** [comment]
I really appreciate your feedback, thank you. Btw, did you notice that the X hotkey now works for apps as well, so you can move multiple windows at once?
I'll think about adding the option to disable unwanted hotkeys, if you have any other suggestions let me know.

**Comment by G-dH** [comment]
Customizable hotkeys were added for most actions. To each editable hotkey action can be assigned up to two characters, one could represent a key press without Shift and second with Shift, that is useful for non [A-Z] keys. You can also delete entries of actions you don't use.
