### ISSUE TITLE
[FEATURE] differentiate `ALT + TAB` and `SUPER + TAB`

### ISSUE THREAD

**Issue by peplocanto** [G-dH/advanced-alttab-window-switcher#80]
I have a multi-monitor setup (4). AATWS saved my life by allowing monitor and workspace isolation. The problem is that now I have to use the mouse to focus on the other screen.

It would be awesome if we could differentiate between ALT + TAB and SUPER + TAB to use the former to switch between apps in the same monitor and the latter to switch among all the apps.

I see that clicking CTRL + F4 while AATWS is active allows for switching between isolated and all apps behavior, but it's a bit of a 'finger-breaking move' and conflicts with the default SUPER behavior in Gnome.

Another solution could be the possibility to map <ALT | SUPER> + TAB + q or just <ALT | SUPER> + q to a different filter (or is it already possible and I missed it?).

Thank you a lot for your awesome extension, and thanks in advance to anyone who wants to help!

**Comment by G-dH** [comment]
Take a look at the _Hotkeys_ tab of the Settings window. You can move AATWS to another monitor using `Ctrl+Tab` or `Shift+Left/Right/Up/Down` in the direction of the target monitor. The default monitor can be determined by the mouse pointer or focused window, based on your choice. You can also switch the filter with a hotkey, the default is `Q`, but you can change it. Different default filters can be set for app and window switchers. One of the fastest ways to navigate among apps and windows is the Search mode. Just type a few letters, and AATWS can find any app or window. It can even automatically switch the filter if needed and search windows from the app switcher.

However, AATWS doesn't support Ctrl+F4. F keys can be used for direct app/window activation.

**Comment by peplocanto** [comment]
perfect...I just associate 'q' as hotkey to change filter. Tnx for your help!
