### ISSUE TITLE
[BUG] App Switcher placement always on top

### ISSUE THREAD

**Issue by ManUtopiK** [G-dH/advanced-alttab-window-switcher#82]
**Describe the bug**
In the Common tab, we can specify the location of the switcher pop-up.
The App Switcher is always on the top of the screen. If I change the location for center or bottom, only the Window Switcher change his location, not the App Switcher.
**To Reproduce**
1. Change the location in the Common tab
3. Open the App Switcher

**Expected behavior**
The App Switcher location should be on the choosen plactement.

**Desktop (please complete the following information):**
 - OS: NixOs and Gnome 45.1 with wayland
 - Extension version 45.3
 - Source of installation : extension.gnome.org

**Comment by G-dH** [comment]
Sounds unlikely since it's actually one switcher only displaying different content.. Can you try resetting AATWS settings on the About tab, if it helps? Any other extensions enabled?

**Comment by ManUtopiK** [comment]
Oh ! I've just discovered what happens. In the Dock Mode tab, the Hot Edge Position is on top, and take precedence over the Placement config. I disabled the Hot Edge Position and now it's in the center.
But it's always in the center. The Placement config has no effect !?

I tried to disable all extensions except AAWS, but this behaviour still remains the same.

Is there a way to save my config, or a config file somewhere ?

**Comment by G-dH** [comment]
> Is there a way to save my config, or a config file somewhere ?

`dconf dump /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/`
or you can redirect the result directly to file:
`dconf dump /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/ > file_name`

Add the the dump here, I'll test your configuration.

**Comment by G-dH** [comment]
Oh, I see it now, you're using Super key to trigger the app switcher.. I'll fix it soon!

**Comment by ManUtopiK** [comment]
Ok, cool. Here's my config :
```
[/]
app-switcher-popup-fav-apps=true
app-switcher-popup-hide-win-counter-for-single-window=true
app-switcher-popup-icon-size=88
app-switcher-popup-raise-first-only=true
app-switcher-popup-search-pref-running=true
app-switcher-popup-show-wins-on-activate=1
app-switcher-popup-sorting=2
app-switcher-popup-titles=false
enable-super=true
hot-edge-mode=0
hot-edge-position=0
hotkey-new-win='N'
show-dash=2
super-double-press-action=1
super-key-mode=2
switcher-popup-hot-keys=false
switcher-popup-hover-select=true
switcher-popup-monitor=1
switcher-popup-pointer=false
switcher-popup-position=2
switcher-popup-preview-selected=2
switcher-popup-status=true
switcher-popup-sync-filter=true
switcher-popup-theme=1
switcher-popup-tooltip-label-scale=125
switcher-popup-tooltip-title=2
switcher-popup-up-down-action=3
switcher-ws-thumbnails=0
win-switch-include-modals=true
win-switch-mark-minimized=true
win-switch-skip-minimized=false
win-switcher-popup-filter=2
win-switcher-popup-icon-size=48
win-switcher-popup-preview-size=160
win-switcher-popup-titles=1
win-switcher-popup-ws-indexes=false
win-thumbnail-scale=20
```

**Comment by ManUtopiK** [comment]
> Oh, I see it now, you're using Super key to trigger the app switcher.. I'll fix it soon!
Yes, I use the Super key.

**Comment by G-dH** [comment]
Since one of the recent updates, the super key should actually open the popup in the dock mode, following the hot edge position and defaulting to the bottom position if hot edge disabled - the center position is a bug. What is your expectation here?

**Comment by G-dH** [comment]
Please, try the latest update from the main branch. Now the position is set by the Common tab option unless the hot edge position is set.

**Comment by ManUtopiK** [comment]
Hi !
I updated to 45.5 and it works has expected now.
I think it's more comprehensive to setting the position by the Common tab option unless the hot edge position is set.
Thanks a lot for your reactivity !
