### ISSUE TITLE
[BUG] entring in dock mode from an empty workspace, swith the actual empty workspace to a window in my previous workspace

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#83]
**Describe the bug**
once i am in an empty workspace, and i try to use use dock mode , my workspace switch immediately to an open window in another workspace, 
i cannot focus in an empty workspace and use dock mode

**To Reproduce**
1. open one or two windows in a same work space
2. switch to another work space (which does not have any open window, even minimized)
3.  enter dock mode by mouse or by super hotkey(if enable)

**Expected behavior**
I want to keep my workspace as my main reference about focusing, and not window,

**Desktop (please complete the following information):**
 - OS: ubuntu 23.04 on gnome 44
 - Version of the extension : 44.7
 - Source of installation : extension manager

**Comment by G-dH** [comment]
Show me your configuration:

`dconf dump /org/gnome/shell/extensions/advanced-alt-tab-window-switcher/`

**Comment by JE-Amouel** [comment]
**here it is** 
[/]
animation-time-factor=150
app-switcher-popup-filter=2
app-switcher-popup-hide-win-counter-for-single-window=true
app-switcher-popup-include-show-apps-icon=false
app-switcher-popup-show-wins-on-activate=0
app-switcher-popup-sorting=2
app-switcher-popup-titles=true
app-switcher-popup-win-counter=true
enable-super=false
hot-edge-mode=1
hot-edge-position=2
hot-edge-width=55
show-dash=0
super-double-press-action=2
super-key-mode=1
switcher-popup-activate-on-hide=false
switcher-popup-ext-app-stable=true
switcher-popup-hot-keys=false
switcher-popup-hover-select=true
switcher-popup-interactive-indicators=true
switcher-popup-pointer-timeout=500
switcher-popup-position=3
switcher-popup-preview-selected=3
switcher-popup-reverse-auto=true
switcher-popup-shift-hotkeys=false
switcher-popup-start-search=false
switcher-popup-status=false
switcher-popup-sync-filter=true
switcher-popup-theme=1
switcher-popup-timeout=100
switcher-popup-tooltip-label-scale=100
switcher-popup-tooltip-title=3
switcher-popup-up-down-action=1
switcher-popup-wrap=true
switcher-ws-thumbnails=1
win-switch-include-modals=false
win-switcher-popup-filter=2
win-switcher-popup-icon-size=40
win-switcher-popup-order=4
win-switcher-popup-preview-size=200
win-switcher-popup-sorting=2
win-switcher-popup-titles=1
win-switcher-popup-ws-indexes=false
win-switcher-single-prev-size=160
win-thumbnail-scale=20
wm-always-activate-focused=false
ws-switch-popup=false

**Comment by G-dH** [comment]
_Settings > Common > Show Selected Window > Show Window Preview_ or _Disable_.  Even if the preview is disabled you can toggle it using Space or KB_0 key.

**Comment by JE-Amouel** [comment]
thanks a lot for your fast answer, it work great!!!.
