### ISSUE TITLE
[FEATURE] more control on workspace indicator

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#84]
it would be good if having displaying option for workspace indicator, like up/down/disable,
i check a lot configuration option but it since to be not possible to disable work space indicator in dock mode or even decide it placement like up or down.
thanks.

and thanks for that much inspired gnome extension.

**Comment by G-dH** [comment]
_Settings_ > _Common_ > _Appearance_ > _Show Workspace Thumbnails_ > [_Disable_ | _Show_ | _Show in Dock Mode Only_]

**Comment by JE-Amouel** [comment]
and what about positioning?

**Comment by JE-Amouel** [comment]
wrokspace indicator  showing on down position only when  common>placement=top, but i do like to have that layout when it placement=Bottom.

**Comment by G-dH** [comment]
It doesn't make any sense to me, the important part is the switcher, and ws thumbnails are just an addition. That means, it's not worth my time at this moment. Sorry.

**Comment by JE-Amouel** [comment]
ho..,  i undertand .
thanks again! your project is awesome.

**Comment by G-dH** [comment]
Thanks for your feedback!
