### ISSUE TITLE
[BUG] Window switcher is invisible if I set "Show Workspace Thumbnais" to "Disable"

### ISSUE THREAD

**Issue by bakai-taalaibek** [G-dH/advanced-alttab-window-switcher#86]
**Describe the bug**
Window switcher is invisible without Workspace thumbnails or status or tooltip titles. It needs one of those to be visible.

**To Reproduce**
1. Open extensions manager
2. Find AATWS extension and click on "Open extension preferences" button (gears)
3. Set "Show Workspace Thumbnais" to "Disable"
4. Now when I press Alt + Tab I don't see the window switcher. 
5. However if I set "Show Workspace Thumbnais" to "Show"  OR set "Tooltip titles" to "Show ..." OR turn on "Show status" then window switcher becomes visible again. 

**Expected behavior**
I want to be able to set "Show Workspace Thumbnais" to "Disable", set "Tooltip titles" to "Disable", turn off "Show status" and still see window switcher. 

**Screenshots**
Window switcher is invisible with these settings:
![image](https://github.com/G-dH/advanced-alttab-window-switcher/assets/121804957/f55386be-da2c-43c0-a092-351b62b17293)

But if I set "Show Workspace Thumbnais" to "Show" it is visible 
![image](https://github.com/G-dH/advanced-alttab-window-switcher/assets/121804957/64a1544f-8c25-41e9-9a0b-1a5dcd63b69f)

**Desktop (please complete the following information):**
 - Ubuntu 23.10
 - Version of the extension 45.6/44
 - Source of installation [extentions manager]

**Additional context**

**Comment by G-dH** [comment]
Thanks, you're right! I'll fix it soon.
