### ISSUE TITLE
[FEATURE] Toggle in settings to disable App Launcher when no windows/apps is opened.

### ISSUE THREAD

**Issue by charleswinata** [G-dH/advanced-alttab-window-switcher#87]
As title say, I don't know how to disable app launcher. I even going to settings and check it one by one and still haven't found it.

Maybe the feature isn't even in there, so I am asking it in here to confirm it.

Thanks.

**Comment by G-dH** [comment]
You're right, there is no such option. Is it really a problem?

**Comment by charleswinata** [comment]
Not that big problem but, I am using dash to dock to launch my apps from homescreen and sometimes my habit of alt tabbing trigger the launcher and I am not even want to launch apps from my pinned app. It's just sometimes bothering me.

**Comment by G-dH** [comment]
Have you tried to use search in the switcher? It's faster than search in the overview.

**Comment by charleswinata** [comment]
oh? how to use that? that's one thing that I don't know how to use... that shortcut thing

**Comment by G-dH** [comment]
The search should be enabled by default after a new installation. In that case, you can start typing while holding the shortcut's modifier key (Alt, Super, etc.). You can disable it on the 'Common' tab of the Settings window, allowing you to use custom hotkeys directly without Shift (there's also the option to always require Shift to avoid accidental actions). However, you can always toggle the search using the Insert key or the custom hotkey (E by default). More information on the search feature is available in the [README](https://github.com/G-dH/advanced-alttab-window-switcher#type-to-search).

**Comment by charleswinata** [comment]
Oh! I've tried it! Need to get used for holding Super/Alt key while searching though,  But It  works way better that I thought.

But yeah, while it works better, I think just pressing Super key and searching for something is already fast enough for me. And my muscle memory need to get used to new shortcut again if I want to get used to it.

And, yeah, I think searching is not a problem for me for now, It's just having option to disable app launcher when no apps/windows opened can help simplify things for me.

**Comment by G-dH** [comment]
If you get used to it, switching between a larger number of windows (even those not open yet) can be a lot faster, and you don't have to think if you use the app switcher or window switcher.
However, I understand your request, but it has a low priority for me.

**Comment by charleswinata** [comment]
Thanks!
