### ISSUE TITLE
search mode Shift+E twice!

### ISSUE THREAD

**Issue by wada3n** [G-dH/advanced-alttab-window-switcher#88]
Hi ,

I'm a big fan of AATWS extension. I've been using it for a while now and I really like the customization options and the search functionality.

I have a question about the keyboard shortcuts. When I press the Super+Tab shortcut to open the window switcher, and then press Shift+E, the switcher doesn't switch to search mode until I press E again. However, if I press Shift+N,a new instance of app window open immediately.

Is this a bug or am I missing something?

Thanks.

**Comment by G-dH** [comment]
Hi, the search should be active by default, allowing you to start typing immediately while holding the Super key and activate the result when you release it. If you prefer to activate the search manually using the hotkey (also the Insert key), which allows you to release the Super key while typing, you can disable the `Search Mode as Default` option in the Settings.

**Comment by wada3n** [comment]
Yes, I know this. What I mean is that when I enter the search mode, I have to press the E key twice, while the other shortcuts work normally. Closing with Shift + W, and opening a window with Shift + N, and so on. 
Only the search mode has to be pressed twice on the E key.

Do you understand me?

**Comment by G-dH** [comment]
If the search is already active, the hotkey disables it, that is expected behavior..

**Comment by wada3n** [comment]
Aah, I get it.
Thank you again for creating such a great extension, t's been an absolute game-changer for my productivity.

**Comment by G-dH** [comment]
Thank you for your feedback :)

**Comment by G-dH** [comment]
However, I'm thinking about it.. Disabling the search is something that nobody really needs, while activating the search so you can release the modifier key could be at least a little bit useful.
