### ISSUE TITLE
Add option "Invert Most Recently Used" for default sorting

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/advanced-alttab-window-switcher#9]
Another great extension!

However, one small issue: if combining this with the great "Custom Hot Corners - Extended" extension and mapping the right edge as a "hot edge" for this switcher, then the mouse will be on the right of the switcher, while the "most recently used" window or app will be on the left...it would be nice if an option to reverse the "most recent"-order could be added to the default sorting choices for the app switcher and window switcher to alleviate this issue. This would also help make the "show selected window/app immediately" option more useful in that use case.

Edit: this might require the item that is selected first when activating the switcher with keyboard to be the second from the right instead of from the left if this option is selected, so that normal "Alt-tabbing" behavior doesn't break.

Thank you for your work!

**Comment by G-dH** [comment]
Actually, I've been tuning the "show selected window immediately" option and related details today, the reversed order came to my mind too and I'll certainly add this option. For example, I changed the initial selection to active window instead of recent if the switcher is triggered by a mouse.

**Comment by UndeadDevel** [comment]
Nice! Might I add the suggestion to have the switcher "spawn" a bit further up when called by the mouse or to add such an option? Right now the switcher's top corner "spawns" where the mouse is, so I have to move the mouse a bit down to compensate when I switch windows.
Also, I think it actually makes sense that the last (not current) window is selected first, but it should be next to the mouse so first in line either right-most or left-most, depending on order setting; the current window should then be last. This would emulate the experience with the keyboard, where if I "alt-tab" my way through the switcher it starts with the last (not current) window and then moves through the less immediate ones until arriving at the current one last.

**Comment by G-dH** [comment]
I also forgot to mention that when AATWS is activated, there is 300 ms time window in which if you press the primary mouse button over the switcher background, initially selected window will be activated no matter what action the button has assigned in the preferences. That means if you open the switcher using a mouse and immediately press the button, recent window window will be activated, if ordering is set to MRU.

**Comment by UndeadDevel** [comment]
Ah, I did not know that; a useful feature, indeed! Might I suggest putting that into the settings (or Help) somewhere so one can become aware of it?
That would also obviate the need to switch the order of the windows in the switcher if the active window is selected first on mouse trigger as long as the user has that "switch to last" time window with primary click.
So AFAIAC this issue can be closed.

**Comment by G-dH** [comment]
The reverse order option has been added already. It kicks in only if the switcher was triggered by a mouse and mouse pointer is near the right edge of the screen.
