### ISSUE TITLE
[BUG] DOCK MODE, HOT EDGE not stay in position when i change the dock position

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#92]
**Describe the bug**
hi, i am currently using ubuntu 24.10 on gnome 45.
i am using dock to panel, and today i decide to change my panel position on the right screen, and since  i did it, if i try again trigger aaws dock by hot edge system, the dock not stay in it position, but continue to go down until it disapear on the bottom of the screen, it looks like the dock position depend on the panel position, is it possible to make depend on the user preference instead?.
thank you.

**Comment by G-dH** [comment]
Please add more information:
- all enabled extensions
- what exact options caused this behavior

**Comment by JE-Amouel** [comment]
this is a list of enabled extensions:
blur-my-shell@aunetx
cronomix@zagortenay333
just-perfection-desktop@just-perfection
quick-settings-tweaks@qwreey
tiling-assistant@leleat-on-github
advanced-alt-tab@G-dH.github.com
arcmenu@arcmenu.com
custom-hot-corners-extended@G-dH.github.com
dash-to-panel@jderose9.github.com
dim-background-windows@stephane-13.github.com
search-light@icedman.github.com
auto-activities@CleoMenezesJr.github.io
gsconnect@andyholmes.github.io
pano@elhan.io
scroll-workspaces@gfxmonk.net

**Comment by JE-Amouel** [comment]
sorry my mouse not show up.

[Screencast_03_07_2024_07:00:56_PM.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/4789ce83-28d3-4f52-ae45-4931834d006b)

**Comment by G-dH** [comment]
Now I understand what's happening. AATWS is attempting to position itself under the panel, but since the panel is vertical ... I'll fix it.

**Comment by JE-Amouel** [comment]
thank you are awesome !!!

**Comment by G-dH** [comment]
Fix is in the repository, you can test it.

**Comment by JE-Amouel** [comment]
work great, yeeeaaaah! 
THANK A LOT.
