### ISSUE TITLE
[BUG] keyboard no longer works in overview

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/advanced-alttab-window-switcher#93]
hi,
I use an extension, auto-activities@CleoMenezesJr.github.io, the purpose of this extension is that when the last window of a workspace is closed, the activities overview is displayed, so when I use the aatws doc to close a window, which is the last one of a workspace, the activities overview is displayed, but while keeping the aatws doc displayed also, so when I try to use my keyboard, neither the search bar of the preview activities nor the aatws doc react to keyboard input, apart from the mouse pointer,

Is it possible to make the aatws doc always hide when the activities preview is displayed?

[Screencast_03_08_2024_08:07:12_PM.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/84618fe0-605f-4e51-a393-32612b9d81bb)

THANKS.

**Comment by JE-Amouel** [comment]
in this demo, I just opened the file explorer, then after, the aaws doc, then thanks to the aaws keybinding I closed the file explorer by pressing the "c" key.

**Comment by G-dH** [comment]
Thanks, I'll fix it.

**Comment by G-dH** [comment]
Done. Please let me know whether the fix works for you.

**Comment by JE-Amouel** [comment]
work great!!!!

[Screencast_03_09_2024_10:51:19_PM.webm](https://github.com/G-dH/advanced-alttab-window-switcher/assets/146543282/d47ac5a3-bed8-4b9f-be04-79e708f96354)

**Comment by JE-Amouel** [comment]
THANK YOU, GREAT JOB! 
LOVE YOU GUY!
