### ISSUE TITLE
[BUG] After today's update, the extension no longer works

### ISSUE THREAD

**Issue by wada3n** [G-dH/advanced-alttab-window-switcher#94]
Hi,
After updating today, the following issues have been observed:

**Unresponsiveness**: The extension no longer responds to typing and searching.
**Window Display**: The extension does not show open windows, even though they are actually changing in the background.

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Version of the extension: 46.1/53
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
Hi. Can you show me your log? Execute in terminal:
`journalctl /usr/bin/{gjs,gnome-shell} -f`
then use AATWS, copy the output and paste it here.

**Comment by wada3n** [comment]
> Journal file /var/log/journal/e2dcb3c17cd14331a85e9b3154b58b6f/system@000612b00232558f-9c97b4e9f7073be5.journal~ is truncated, ignoring file.
Mar 13 18:03:16 fedora gnome-shell[2289]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-shell[2289]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Mar 13 18:03:53 fedora gnome-character[4344]: JS LOG: Characters Application started
Mar 13 18:03:55 fedora gnome-shell[2289]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Mar 13 18:04:04 fedora gnome-character[4344]: JS LOG: Characters Application exiting
Mar 13 18:04:17 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1025:22
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:18 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _itemEnteredHandler@resource:///org/gnome/shell/ui/switcherPopup.js:258:14
                                          _itemEntered@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:840:18
                                          _itemEntered@resource:///org/gnome/shell/ui/switcherPopup.js:565:14
                                          _onItemMotion@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/switcherList.js:200:18
                                          addItem/<@resource:///org/gnome/shell/ui/switcherPopup.js:453:49
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:21 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:993:30
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:22 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:22 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:22 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:23 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:993:30
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:23 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:24 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:993:30
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:25 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:27 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1025:22
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:27 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _keyPressHandler@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2024:22
                                          vfunc_key_press_event@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1867:18
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Mar 13 18:04:28 fedora gnome-shell[2289]: JS ERROR: TypeError: Util.WindowPreview is not a constructor
                                          _showPreview@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:2675:32
                                          _select@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1591:18
                                          _initialSelection@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1025:22
                                          _showPopup@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:601:18
                                          show@file:///home/andalus/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:500:18
                                          _startSwitcher@resource:///org/gnome/shell/ui/windowManager.js:1630:23
                                          @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by G-dH** [comment]
Btw, have you restarted GNOME Shell after the update?

**Comment by wada3n** [comment]
Yes, I have restarted GNOME Shell after the update. I even tried restarting my computer, but the issue persists.

I hope this information is helpful. Please let me know if you need any further information.
Thanks

**Comment by G-dH** [comment]
If you disable `Show Selected Window` option, any other errors?

**Comment by wada3n** [comment]
Everything is working perfectly now!

**Comment by G-dH** [comment]
A bug in my update script caused `util.js` not to be updated. Additionally, I've fixed another preview-related bug that I noticed. I'm sending the updated version for review on ego.

**Comment by wada3n** [comment]
Thank you for the quick response and fix. I appreciate your hard work and dedication to this extension.

**Comment by ConsularParadi** [comment]
Hi, I am also facing the same issue in fedora 39 after I rebooted my laptop post an update 

Here is my journalctl log
ar 15 19:25:53 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845102.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/org.gnome.Extensions/174845102.json!
Mar 15 19:25:53 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845111.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/Chromium-browser/174845111.json!
Mar 15 19:25:54 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845136.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/kitty/174845136.json!
Mar 15 19:25:57 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session summary.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/summary.json!
Mar 15 19:25:57 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session summary.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/summary.json!
Mar 15 19:25:57 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845102.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/org.gnome.Extensions/174845102.json!
Mar 15 19:25:57 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845136.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/kitty/174845136.json!
Mar 15 19:25:58 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session summary.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/summary.json!
Mar 15 19:25:59 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845102.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/org.gnome.Extensions/174845102.json!
Mar 15 19:25:59 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845136.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/kitty/174845136.json!
Mar 15 19:26:02 fedora gnome-shell[6014]: [INFO   ][Another window session manager] Session 174845136.json saved to /home/consularparadi/.config/another-window-session-manager/currentSession/kitty/174845136.json!
Mar 15 19:26:02 fedora gnome-character[20172]: JS LOG: Characters Application exiting
