### ISSUE TITLE
[Help] Is there any way to have combine apps and their windows during selection? Combine app switcher and window switcher into one.

### ISSUE THREAD

**Issue by radiorambo** [G-dH/advanced-alttab-window-switcher#95]
If my browser has multiple windows, first i have select browser app and then select a window, instead is there any way to have windows in same row as apps during switching, Combine app switcher and window switcher into one.

**Comment by G-dH** [comment]
You can open the app switcher, select an app, and then use the key above the Tab key (or the key you've designated for switching between windows of an application) to switch to the window you need.

Or you can open the window switcher and use the key above the Tab to switch between the first windows of each application. Once you use the key, the window thumbnails reorder by application.

Another option is to use the search feature to find a window by its title in both the app and window switcher.

**Comment by radiorambo** [comment]
I know the first and second option you mentioned were mostly similar to stock gnome options, which i have been using all these days, but when I in hurry and I have a lot of apps and windows, it confuses my brain. So i was searching for an extension which would combine those two in a single row. And search feature is alot for me. 

Maybe since you didn't mention any option in the extension to combine those, i presume option isn't available yet, but if you ever feel of implementing new features, consider this. 

And thanks for the quick reply,

**Comment by G-dH** [comment]
I believe that grouping windows by apps is what you're asking for, if I understand your request correctly. You can either use the second method I suggested, or you can make it the default behavior by selecting the window switcher option 'Default Grouping' > 'Applications'. In this scenario, you can switch between apps and windows in one row by using two hotkeys. Additionally, you can experiment with the distribution of apps across workspaces and adjust AATWS filter settings on the fly by a filter hotkey.

The 'type to search' feature is the most efficient way for me to switch windows in most cases. I simply open the switcher, type two letters, and the window I need is selected. There's no need to stare at a list of windows when they all look alike. This feature can also search by app names, not just window titles, and you can combine both. Even if you set AATWS to filter windows of the current workspace or monitor, it can automatically switch the filter to find a window on any other workspace if no window on the current one matches the search pattern. This means that I'm usually able to switch to any window without even looking at the switcher, regardless of where the window is or isn't on the list.

**Comment by radiorambo** [comment]
What i need is "no windows grouping". I took a deeper look into settings again, and found the option I am in need for.

![image](https://github.com/G-dH/advanced-alttab-window-switcher/assets/64721943/ada1faf2-64ed-4bbb-9b2b-a8f3e603c9b3)

But the only problem now is, there is no way to change default mode, it always defaults to app mode and then press `shift + z` to switch to windows mode, but i want it to default it to windows mode on `super + tab`, but i couldn't find a option for it. 

Is there any way to set windows mode as default always.

**Comment by G-dH** [comment]
Read again the last paragraph of my previous comment.

**Comment by radiorambo** [comment]
Great, you fixed my problem. I never knew that gnome has this option already. I wonder how I never paid attention to it.  And I presume, this is the case with most. Maybe you should add an option to set keyboard shortcut in the extension too, or may be a helpful text in hotkeys section to also check in settings. 

And any way your support in fixing problem is commendable. And I also took a look into your profile. Your contributions in gnome extensions is on another level. Inspired me alot as a JS developer. Keep going.

**Comment by G-dH** [comment]
You confused me with the single row. And you're right, you're not alone, that's why I added the last paragraph. I also mentioned this fact everywhere - in the description, README, in the Settings window on the `App Switcher` and `Window Switcher` tabs with the full paths to the shortcuts, ... But people only see what they expect to see :)

Thanks for your feedback!

**Comment by radiorambo** [comment]
HaHa. I checked, you did mention everywhere. But they look more like a "safe to ignore" text than that seeks attention. Or maybe you should add option to reconfigure system keyboard shortcuts from extension itself. Or maybe dedicate the first opening tab in extension like a "mini readme" containing a check list items to look if encountered bugs or issues or missing features, difference between windows, apps, and workspaces and also filtering, grouping. or maybe a github issue template checklist. I think you know it better. 

I may be over advising but this helped me alot in life and in work. "Put things, where you look when you need them, than where they belong".

**Comment by G-dH** [comment]
Thanks, I should focus more on documentation and promotion in general, but there's always something I can code.. :)
