### ISSUE TITLE
[FEATURE] activate search mode automatically

### ISSUE THREAD

**Issue by fountainer** [G-dH/advanced-alttab-window-switcher#97]
**Describe the bug**
The "Search Mode as Deafult"  On the "Common" tab is switched on. However, I cannot activate search mode automatically when pressing `Super+Tab`.  I have to press "Shift+E" to active search mode.

**To Reproduce**

**Expected behavior**
Automatically enabling search mode when pressing `Super+Tab`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Version of the extension: 46.1/54
 - Source of installation: extension.gnome.org

**Additional context**

**Comment by G-dH** [comment]
The search mode should be active, just start typing while still holding the modifier key of your switcher shortcut. It allows you to activate the selected search results by releasing the modifier key as usual. Use the search toggle hotkey only if you want to release the modifier key without activating the result.

**Comment by G-dH** [comment]
1. If it worked as you're suggesting, AATWS would cease to be usable for quick switching without pressing the Enter key to activate the selected item. However, if you set AATWS to replace the overview upon pressing the Super key, then it functions in that manner.
2. You can enable the `Show Window Titles` option in the Settings, although there is usually insufficient space under the switcher item for the entire title.

If you require a vertical list of open windows, you can either utilize my *WSP (Window Search Provider)* extension, which allows you to search and list all open windows from the Activities overview, or you can try the *Switcher* extension.

**Comment by fountainer** [comment]
Thank you. I'll try them and check which is best suited for me.
