### ISSUE TITLE
How can I set current monitor only when there is a sinle window.

### ISSUE THREAD

**Issue by rasulali** [G-dH/advanced-alttab-window-switcher#99]
I know this sounds stupid but I use super+tab for workspace switching and alt+tab for windows switching. when there is a single window and I accidentally press alt+tab it defaults back to all windows and disables the current monitor only windows switching. How can I disable this feature so if there is single window it justs show that window like gnome's default behavior

**Comment by G-dH** [comment]
It doesn't sound stupid to me, as I'm using the Super+Tab app switcher to navigate between workspaces myself, while having the Alt+Tab window switcher filter set for the current monitor. However, perhaps I don't fully understand your configuration. When there's only one window on the monitor, AATWS can automatically switch the filter to 'workspace/all' only if you press Alt+Tab twice. This filter switching is temporary and doesn't affect the setting for the next use of the switcher.

**Comment by rasulali** [comment]
yess, thats correct. But is there option or something I can change in code to disable that behavior as I'm always pressing it multiple times

**Comment by G-dH** [comment]
I'll add the option.
